# to test Mo with log tail model turned on.
logservices = [
    "./etc/launch-test-push-model/log.toml",
]

dnservices = [
    "./etc/launch-test-push-model/dn.toml"
]

cnservices = [
    "./etc/launch-test-push-model/cn.toml"
]