FROM golang:1.18-alpine3.14 as builder

RUN apk add --no-cache \
    wget \
    make \
    git \
    gcc \
    binutils-gold \
    musl-dev

RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64 \
 && chmod +x /usr/local/bin/dumb-init

RUN mkdir -p /go/src/github.com/matrixorigin/mysql-tester

RUN git clone https://github.com/matrixorigin/mysql-tester.git /go/src/github.com/matrixorigin/mysql-tester

WORKDIR /go/src/github.com/matrixorigin/mysql-tester

RUN go mod download

RUN make build


FROM alpine

RUN apk add --no-cache bash

COPY --from=builder /go/src/github.com/matrixorigin/mysql-tester/mysql-tester /mysql-tester
COPY --from=builder /usr/local/bin/dumb-init /usr/local/bin/dumb-init
COPY --from=builder /go/src/github.com/matrixorigin/mysql-tester/r /r
COPY  --from=builder /go/src/github.com/matrixorigin/mysql-tester/t /t

WORKDIR /

ENTRYPOINT ["/usr/local/bin/dumb-init", "/mysql-tester"]
