drop database if exists test01;
drop database if exists test03;
drop database if exists test04;
drop database if exists test05;
drop database if exists `测试数据库`;
create database test01;
create database IF NOT EXISTS test01;
create database `测试数据库`;
#create database test03 default character set utf8 collate utf8_general_ci encryption 'Y';
#create database test04 character set=utf8 collate=utf8_general_ci encryption='N';
show databases;
drop database if exists test01;
drop database if exists test03;
drop database if exists test04;
drop database if exists test05;
drop database if exists `测试数据库`;
drop database if exists `ABCDE`;
drop database if exists `abcde`;
drop database if exists db_with_no_tables_and_an_unrelated_file_in_data_directory;
create database `ABCDE`;
create database `abcde`;
create database db_with_no_tables_and_an_unrelated_file_in_data_directory;
show databases;
drop database `ABCDE`;
drop database `abcde`;
drop database db_with_no_tables_and_an_unrelated_file_in_data_directory;
