# service node type, [DN|CN|LOG]
service-type = "DN"

[log]
level = "info"
format = "json"
max-size = 512


[hakeeper-client]
service-addresses = [
    "127.0.0.1:32001",
    "127.0.0.1:32011",
    "127.0.0.1:32021",
]

[[fileservice]]
name = "LOCAL"
backend = "MEM"

[[fileservice]]
name = "SHARED"
backend = "MEM"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"
data-dir = "mo-data/local/etl"

[dn]
uuid = "dd4dccb4-4d3c-41f8-b482-5251dc7a41bf"
listen-address = "127.0.0.1:41010"
service-address = "127.0.0.1:41010"

[dn.Txn]

[dn.Txn.Storage]
# txn storage backend implementation. [TAE|MEM]
backend = "MEM"

[observability]
statusPort = 8001
