// Code generated by command: go run avx2.go -out add/avx2.s -stubs add/avx2_stubs.go. DO NOT EDIT.

package vectorize

func int8AddAvx2Asm(x []int8, y []int8, r []int8)

func int8AddScalarAvx2Asm(x int8, y []int8, r []int8)

func int16AddAvx2Asm(x []int16, y []int16, r []int16)

func int16AddScalarAvx2Asm(x int16, y []int16, r []int16)

func int32AddAvx2Asm(x []int32, y []int32, r []int32)

func int32AddScalarAvx2Asm(x int32, y []int32, r []int32)

func int64AddAvx2Asm(x []int64, y []int64, r []int64)

func int64AddScalarAvx2Asm(x int64, y []int64, r []int64)

func uint8AddAvx2Asm(x []uint8, y []uint8, r []uint8)

func uint8AddScalarAvx2Asm(x uint8, y []uint8, r []uint8)

func uint16AddAvx2Asm(x []uint16, y []uint16, r []uint16)

func uint16AddScalarAvx2Asm(x uint16, y []uint16, r []uint16)

func uint32AddAvx2Asm(x []uint32, y []uint32, r []uint32)

func uint32AddScalarAvx2Asm(x uint32, y []uint32, r []uint32)

func uint64AddAvx2Asm(x []uint64, y []uint64, r []uint64)

func uint64AddScalarAvx2Asm(x uint64, y []uint64, r []uint64)

func float32AddAvx2Asm(x []float32, y []float32, r []float32)

func float32AddScalarAvx2Asm(x float32, y []float32, r []float32)

func float64AddAvx2Asm(x []float64, y []float64, r []float64)

func float64AddScalarAvx2Asm(x float64, y []float64, r []float64)
