// Code generated by command: go run avx512.go -out plus/avx512.s -stubs plus/avx512_stubs.go. DO NOT EDIT.

package plus

func int8PlusAvx512Asm(x []int8, y []int8, r []int8)

func int8PlusScalarAvx512Asm(x int8, y []int8, r []int8)

func int16PlusAvx512Asm(x []int16, y []int16, r []int16)

func int16PlusScalarAvx512Asm(x int16, y []int16, r []int16)

func int32PlusAvx512Asm(x []int32, y []int32, r []int32)

func int32PlusScalarAvx512Asm(x int32, y []int32, r []int32)

func int64PlusAvx512Asm(x []int64, y []int64, r []int64)

func int64PlusScalarAvx512Asm(x int64, y []int64, r []int64)

func uint8PlusAvx512Asm(x []uint8, y []uint8, r []uint8)

func uint8PlusScalarAvx512Asm(x uint8, y []uint8, r []uint8)

func uint16PlusAvx512Asm(x []uint16, y []uint16, r []uint16)

func uint16PlusScalarAvx512Asm(x uint16, y []uint16, r []uint16)

func uint32PlusAvx512Asm(x []uint32, y []uint32, r []uint32)

func uint32PlusScalarAvx512Asm(x uint32, y []uint32, r []uint32)

func uint64PlusAvx512Asm(x []uint64, y []uint64, r []uint64)

func uint64PlusScalarAvx512Asm(x uint64, y []uint64, r []uint64)

func float32PlusAvx512Asm(x []float32, y []float32, r []float32)

func float32PlusScalarAvx512Asm(x float32, y []float32, r []float32)

func float64PlusAvx512Asm(x []float64, y []float64, r []float64)

func float64PlusScalarAvx512Asm(x float64, y []float64, r []float64)
