drop table if exists t1;
create table t1(a int);
insert into t1 values(1),(2),(3),(4);
select count(*) from t1;
begin;
truncate t1;
truncate t1;
truncate t1;
truncate t1;
truncate t1;
truncate t1;
show tables;
commit;
show tables;
select count(*) from t1;
-----------------------
drop table if exists t1;
begin;
create table t1(a int);
drop table t1;
create table t1(a int);
drop table t1;
create table t1(a int);
drop table t1;
create table t1(a int);
drop table t1;
commit;
show tables;
-----------------------
drop table if exists t1;
begin;
create table t1(a int);
create table t2(a int);
create table t3(a int);
create table t4(a int);
drop table t1;
drop table t2;
drop table t3;
drop table t4;
commit;
show tables;