version: '3.9'

services:
  cn-0:
    container_name: cn-0
    build:
      context: ../../
      dockerfile: ./optools/images/Dockerfile
      args:
        GOPROXY: "https://proxy.golang.com.cn,direct"
    image: matrixorigin/matrixone:nightly-64bc606f
    entrypoint: ["/mo-service", "-cfg", "/config/cn-0.toml"]
    depends_on:
      - dn
    ports:
      - "6001:6001"
      - "6002"
    restart: on-failure
    volumes:
      - ../../etc/launch-mo-compose-s3/config:/config
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    tty: true
    networks:
      monet:

  dn:
    container_name: dn
    build:
      context: ../../
      dockerfile: ./optools/images/Dockerfile
      args:
        GOPROXY: "https://proxy.golang.com.cn,direct"
    image: matrixorigin/matrixone:nightly-64bc606f
    entrypoint: ["/mo-service", "-cfg", "/config/dn.toml"]
    depends_on:
      - logservice
    ports:
      - "41010"
    restart: on-failure
    tty: true
    volumes:
      - ../../etc/launch-mo-compose-s3/config:/config
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    networks:
      monet:

  logservice:
    container_name: logservice
    build:
      context: ../../
      dockerfile: ./optools/images/Dockerfile
      args:
        GOPROXY: "https://proxy.golang.com.cn,direct"
    image: matrixorigin/matrixone:nightly-64bc606f
    entrypoint: ["/mo-service", "-cfg", "/config/log.toml"]
    ports:
      - "32000"
      - "32001"
      - "32002"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    restart: on-failure
    volumes:
      - ../../etc/launch-mo-compose-s3/config:/config
    tty: true    
    networks:
      monet:
        ipv4_address: 179.19.0.4

networks:
  monet:
    driver: bridge
    ipam:
      config:
        - subnet: 179.19.0.0/16