header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Matrix Origin
  paths-ignore:
    - 'docs/'
    - 'optools/'
    - '**/go.mod'
    - '**/go.sum'
    - 'LICENSE'
    - '**/*.csv'
    - '**/*.proto'
    - 'Makefile'
    - 'LICENSES/'
    - '**/*.toml'
    - '**/*.s'
    - '**/*.sql'
    - '**/.gitignore'
    - '**/Dockerfile'
    - '.github/'
    - '.golangci.yml'
    - '.editorconfig'
    - '**/*.md'
    - 'proto/'
  comment: on-failure
