queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by<=0"
      - "check-success=Lint Docs"
      - "check-success=UT Test on Ubuntu/x64"
      - "check-success=UT Test on Darwin/x86"
      - "check-success=UT Test on Linux/Arm"
      - "check-success=BVT Test on Ubuntu/x64"
      - "check-success=BVT Test on Linux/Arm"
      - "check-success=BVT Test on Darwin/x86"
      - "check-success=BVT RACE Test on CentOS/x64"
      - "check-success=SCA Test on Ubuntu/x64"  
    actions:
      queue:
        name: default
        method: squash

  - name: label for Bug
    conditions: 
      - body~=(?m)- \[(?i)x\] BUG
    actions:
      label:
        add:
          - kind/bug
  - name: label for Feature
    conditions: 
      - body~=(?m)- \[(?i)x\] Feature
    actions:
      label:
        add:
          - kind/feature
  - name: label for Improvement
    conditions: 
      - body~=(?m)- \[(?i)x\] Improvement
    actions:
      label:
        add:
          - kind/enhancement
  - name: label for Documentation
    conditions: 
      - body~=(?m)- \[(?i)x\] Documentation
    actions:
      label:
        add:
          - kind/documentation
  - name: label for Test and CI
    conditions: 
      - body~=(?m)- \[(?i)x\] Test and CI
    actions:
      label:
        add:
          - kind/test-ci
  - name: label for Code Refactoring
    conditions: 
      - body~=(?m)- \[(?i)x\] Code Refactoring
    actions:
      label:
        add:
          - kind/refactor
  - name: label for API-change
    conditions: 
      - body~=(?m)- \[(?i)x\] API-change
    actions:
      label:
        add:
          - kind/api-change