queue_rules:
  - name: main
    branch_protection_injection_mode: queue
    queue_conditions:
      - "#changes-requested-reviews-by<=0"
      - label!=do-not-merge/wip
      - base=main
    merge_conditions: []
    checks_timeout: 4h
    merge_method: squash
    commit_message_template: |
        {{ title }} (#{{ number }})

        {{ body.split("___\n\n### **PR Type**")[0] | trim | get_section("## What this PR does / why we need it:") }}

        Approved by: @{{ approved_reviews_by | join(', @') }}
  - name: release-1.2
    branch_protection_injection_mode: queue
    queue_conditions:
      - "#changes-requested-reviews-by<=0"
      - label!=do-not-merge/wip
      - base=1.2-dev
      - approved-reviews-by=sukki37
    merge_conditions: []
    checks_timeout: 4h
    merge_method: squash
    commit_message_template: |
        {{ title }} (#{{ number }})

        {{ body.split("___\n\n### **PR Type**")[0] | trim | get_section("## What this PR does / why we need it:") }}

        Approved by: @{{ approved_reviews_by | join(', @') }}

pull_request_rules:
  - name: Auto update branch
    conditions:
      - created-at>=00:10 ago
    actions:
      update: 

  - name: Auto Request Reviewer For 1.2-dev
    conditions:
      - base!=main
    actions:
      request_reviews:
        users:
          - sukki37

  - name: label for Bug
    conditions: 
      - body~=(?im)- \[x\] BUG
    actions:
      label:
        add:
          - kind/bug
  - name: label for Feature
    conditions: 
      - body~=(?im)- \[x\] Feature
    actions:
      label:
        add:
          - kind/feature
  - name: label for Improvement
    conditions: 
      - body~=(?im)- \[x\] Improvement
    actions:
      label:
        add:
          - kind/enhancement
  - name: label for Documentation
    conditions: 
      - body~=(?im)- \[x\] Documentation
    actions:
      label:
        add:
          - kind/documentation
  - name: label for Test and CI
    conditions: 
      - body~=(?im)- \[x\] Test and CI
    actions:
      label:
        add:
          - kind/test-ci
  - name: label for Code Refactoring
    conditions: 
      - body~=(?im)- \[x\] Code Refactoring
    actions:
      label:
        add:
          - kind/refactor
  - name: label for API-change
    conditions: 
      - body~=(?im)- \[x\] API-change
    actions:
      label:
        add:
          - kind/api-change
