pull_request_rules:
  - name: Reviewed for pull request
    conditions:
      - base=main
      - "status-success=Build on CentOS/x64"
      - "#approved-reviews-by>=1"
    actions:
      label:
        add:
          - reviewed
  - name: automatic update
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
    actions:
      update:
