// Copyright 2021 - 2022 Matrix Origin
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package function

import (
	"testing"

	"github.com/stretchr/testify/require"
)

// all fixed function ids defined at 2024-12-12
var predefinedFunids = map[int]int{
	EQUAL:              0,
	NOT_EQUAL:          1,
	GREAT_THAN:         2,
	GREAT_EQUAL:        3,
	LESS_THAN:          4,
	LESS_EQUAL:         5,
	BETWEEN:            6,
	UNARY_PLUS:         7,
	UNARY_MINUS:        8,
	UNARY_TILDE:        9,
	PLUS:               10,
	MINUS:              11,
	MULTI:              12,
	DIV:                13,
	INTEGER_DIV:        14,
	MOD:                15,
	CONCAT:             16,
	AND:                17,
	OR:                 18,
	XOR:                19,
	NOT:                20,
	CAST:               21,
	BIT_CAST:           22,
	IS:                 23,
	ISNOT:              24,
	ISNULL:             25,
	ISNOTNULL:          26,
	ISTRUE:             27,
	ISNOTTRUE:          28,
	ISFALSE:            29,
	ISNOTFALSE:         30,
	ISEMPTY:            31,
	NOT_IN_ROWS:        32,
	OP_BIT_AND:         33,
	OP_BIT_OR:          34,
	OP_BIT_XOR:         35,
	OP_BIT_SHIFT_LEFT:  36,
	OP_BIT_SHIFT_RIGHT: 37,

	ABS:               38,
	ACOS:              39,
	ADDDATE:           40,
	ADDTIME:           41,
	AES_DECRYPT:       42,
	AES_ENCRYPT:       43,
	ANY_VALUE:         44,
	APPROX_COUNT:      45,
	ARRAY_AGG:         46,
	ARRAY_APPEND:      47,
	ARRAY_CAT:         48,
	ARRAY_CONTAINS:    49,
	ARRAY_POSITION:    50,
	ARRAY_SIZE:        51,
	ASCII:             52,
	ASIN:              53,
	ASSERT:            54,
	ATAN:              55,
	ATAN2:             56,
	AVG:               57,
	AVG_TW_CACHE:      58,
	AVG_TW_RESULT:     59,
	BASE64_DECODE:     60,
	BASE64_ENCODE:     61,
	BIT_AND:           62,
	BIT_LENGTH:        63,
	BIT_NOT:           64,
	BIT_OR:            65,
	BIT_XOR:           66,
	BITAGG_AND:        67,
	BITAGG_OR:         68,
	BOOLAGG_AND:       69,
	BOOLAGG_OR:        70,
	CASE:              71,
	CEIL:              72,
	CHR:               73,
	COALESCE:          74,
	FIELD:             75,
	CONCAT_WS:         76,
	CONTAINS:          77,
	CORR:              78,
	COS:               79,
	COT:               80,
	CRC32:             81,
	COUNT:             82,
	COUNT_IF:          83,
	COVAR_POP:         84,
	COVAR_SAMPLE:      85,
	CONVERT_TZ:        86,
	CUME_DIST:         87,
	CURRENT_DATE:      88,
	CURRENT_TIMESTAMP: 89,
	DATE_FROM_PARTS:   90,
	DATE_PART:         91,
	DATEADD:           92,
	DATEDIFF:          93,
	TIMEDIFF:          94,
	TIMESTAMPDIFF:     95,
	DENSE_RANK:        96,
	MO_WIN_DIVISOR:    97,
	EMPTY:             98,
	ENDSWITH:          99,
	EXP:               100,
	FINDINSET:         101,
	FIRST_VALUE:       102,
	FLOOR:             103,
	GREATEST:          104,
	GROUPING:          105,
	HASH:              106,
	HASH_AGG:          107,
	HEX_DECODE:        108,
	HEX_ENCODE:        109,
	HEX:               110,
	UNHEX:             111,
	MD5:               112,
	IFF:               113,
	IFNULL:            114,
	ILIKE:             115,
	ILIKE_ALL:         116,
	ILIKE_ANY:         117,
	IN:                118,
	LAG:               119,
	LAST_VALUE:        120,
	LEAD:              121,
	LEAST:             122,
	LEFT:              123,
	LENGTH:            124,
	LENGTH_UTF8:       125,
	LIKE:              126,
	LIKE_ALL:          127,
	LIKE_ANY:          128,
	LN:                129,
	NOT_IN:            130,
	LOG:               131,
	LOG2:              132,
	LOG10:             133,
	LOWER:             134,
	LPAD:              135,
	LTRIM:             136,
	MAX:               137,
	MEDIAN:            138,
	MIN:               139,
	MODE:              140,
	MONTH:             141,
	NORMAL:            142,
	NTH_VALUE:         143,
	NTILE:             144,
	NULLIF:            145,
	PERCENT_RANK:      146,
	PI:                147,
	POSITION:          148,
	POW:               149,
	PREFIX_EQ:         150,
	PREFIX_IN:         151,
	PREFIX_BETWEEN:    152,
	RADIAN:            153,
	RANDOM:            154,
	RANK:              155,
	REGEXP:            156,
	REGEXP_INSTR:      157,
	REGEXP_LIKE:       158,
	REGEXP_REPLACE:    159,
	REGEXP_SUBSTR:     160,
	REG_MATCH:         161,
	NOT_REG_MATCH:     162,
	REPEAT:            163,
	REPLACE:           164,
	REVERSE:           165,
	RIGHT:             166,
	ROUND:             167,
	ROW_NUMBER:        168,
	RPAD:              169,
	RTRIM:             170,
	SIGN:              171,
	SIN:               172,
	SINH:              173,
	SPACE:             174,
	SPLIT:             175,
	SPLIT_PART:        176,
	SQRT:              177,
	STARCOUNT:         178,
	STARTSWITH:        179,
	STDDEV_POP:        180,
	STDDEV_SAMPLE:     181,
	SUBSTR:            182,
	SUM:               183,
	SYSDATE:           184,
	GROUP_CONCAT:      185,
	TAN:               186,
	TO_DATE:           187,
	STR_TO_DATE:       188,
	TO_INTERVAL:       189,
	TRANSLATE:         190,
	TRIM:              191,
	UNIFORM:           192,
	SHA1:              193,
	SHA2:              194,
	UTC_TIMESTAMP:     195,
	UNIX_TIMESTAMP:    196,
	FROM_UNIXTIME:     197,
	UPPER:             198,
	VAR_POP:           199,
	VAR_SAMPLE:        200,
	LAST_DAY:          201,
	MAKEDATE:          202,
	DATE:              203,
	TIME:              204,
	DAY:               205,
	DAYOFYEAR:         206,
	DAYOFWEEK:         207,
	INTERVAL:          208,
	EXTRACT:           209,
	OCT:               210,
	SUBSTRING:         211,
	ENCODE:            212,
	DECODE:            213,
	TO_BASE64:         214,
	FROM_BASE64:       215,
	SUBSTRING_INDEX:   216,
	WEEK:              217,
	WEEKDAY:           218,
	YEAR:              219,
	HOUR:              220,
	MINUTE:            221,
	SECOND:            222,
	TO_DAYS:           223,
	TO_SECONDS:        224,

	DATE_ADD:              225,
	DATE_SUB:              226,
	APPROX_COUNT_DISTINCT: 227,

	LOAD_FILE:            228,
	SAVE_FILE:            229,
	DATABASE:             230,
	USER:                 231,
	CONNECTION_ID:        232,
	CHARSET:              233,
	CONVERT:              234,
	CURRENT_ROLE:         235,
	FOUND_ROWS:           236,
	ICULIBVERSION:        237,
	LAST_INSERT_ID:       238,
	LAST_QUERY_ID:        239,
	LAST_UUID:            240,
	ROLES_GRAPHML:        241,
	ROW_COUNT:            242,
	VERSION:              243,
	COLLATION:            244,
	CURRENT_ACCOUNT_ID:   245,
	CURRENT_ACCOUNT_NAME: 246,
	CURRENT_ROLE_ID:      247,
	CURRENT_ROLE_NAME:    248,
	CURRENT_USER_ID:      249,
	CURRENT_USER_NAME:    250,

	TIMESTAMP:            251,
	DATE_FORMAT:          252,
	JSON_EXTRACT:         253,
	JSON_EXTRACT_STRING:  254,
	JSON_EXTRACT_FLOAT64: 255,
	JSON_QUOTE:           256,
	JSON_UNQUOTE:         257,
	JSON_ROW:             258,

	JQ:       259,
	TRY_JQ:   260,
	WASM:     261,
	TRY_WASM: 262,
	FORMAT:   263,
	SLEEP:    264,
	INSTR:    265,
	LOCATE:   266,

	UUID:           267,
	SERIAL:         268,
	SERIAL_FULL:    269,
	SERIAL_EXTRACT: 270,
	BIN:            271,

	ENABLE_FAULT_INJECTION:  272,
	DISABLE_FAULT_INJECTION: 273,
	ADD_FAULT_POINT:         274,
	REMOVE_FAULT_POINT:      275,
	TRIGGER_FAULT_POINT:     276,
	MO_WIN_TRUNCATE:         277,

	MO_MEMORY_USAGE:                278,
	MO_ENABLE_MEMORY_USAGE_DETAIL:  279,
	MO_DISABLE_MEMORY_USAGE_DETAIL: 280,

	MO_CTL: 281,

	MO_SHOW_VISIBLE_BIN:      282,
	MO_SHOW_VISIBLE_BIN_ENUM: 283,
	MO_SHOW_COL_UNIQUE:       284,

	MO_TABLE_ROWS:    285,
	MO_TABLE_SIZE:    286,
	MO_TABLE_COL_MAX: 287,
	MO_TABLE_COL_MIN: 288,

	MO_LOG_DATE:    289,
	PURGE_LOG:      290,
	MO_ADMIN_NAME:  291,
	MO_CU:          292,
	MO_CU_V1:       293,
	MO_EXPLAIN_PHY: 294,

	GIT_VERSION:   295,
	BUILD_VERSION: 296,

	VALUES:                        297,
	BINARY:                        298,
	INTERNAL_CHAR_LENGTH:          299,
	INTERNAL_CHAR_SIZE:            300,
	INTERNAL_NUMERIC_PRECISION:    301,
	INTERNAL_NUMERIC_SCALE:        302,
	INTERNAL_DATETIME_SCALE:       303,
	INTERNAL_COLUMN_CHARACTER_SET: 304,
	INTERNAL_AUTO_INCREMENT:       305,

	CAST_INDEX_TO_VALUE:       306,
	CAST_VALUE_TO_INDEX:       307,
	CAST_INDEX_VALUE_TO_INDEX: 308,

	CAST_NANO_TO_TIMESTAMP: 309,
	CAST_RANGE_VALUE_UNIT:  310,

	NEXTVAL: 311,
	SETVAL:  312,
	CURRVAL: 313,
	LASTVAL: 314,

	SUMMATION:         315,
	L1_NORM:           316,
	L2_NORM:           317,
	INNER_PRODUCT:     318,
	COSINE_SIMILARITY: 319,
	VECTOR_DIMS:       320,
	NORMALIZE_L2:      321,
	L2_DISTANCE:       322,
	L2_DISTANCE_SQ:    323,
	COSINE_DISTANCE:   324,
	CLUSTER_CENTERS:   325,
	SUB_VECTOR:        326,

	PYTHON_UDF: 327,

	MO_CPU:      328,
	MO_MEMORY:   329,
	MO_CPU_DUMP: 330,

	BITMAP_BIT_POSITION:  331,
	BITMAP_BUCKET_NUMBER: 332,
	BITMAP_COUNT:         333,
	BITMAP_CONSTRUCT_AGG: 334,
	BITMAP_OR_AGG:        335,

	FULLTEXT_MATCH:       336,
	FULLTEXT_MATCH_SCORE: 337,

	JSON_SET:     338,
	JSON_INSERT:  339,
	JSON_REPLACE: 340,

	FAULT_INJECT: 341,

	L2_DISTANCE_XC:    342,
	L2_DISTANCE_SQ_XC: 343,

	TS_TO_TIME: 344,
	STRCMP:     345,

	STARLARK:     346,
	TRY_STARLARK: 347,

	FUNCTION_END_NUMBER: 348,
}

func Test_funids(t *testing.T) {
	check := func(fid int) {
		if _, ok := predefinedFunids[fid]; !ok {
			require.Failf(t, "no functionid in 'predefinedFunids'", "put funtion id %d into 'predefinedFunids'", fid)
		} else {
			require.Equal(t, fid, predefinedFunids[fid])
		}
		require.Greater(t, FUNCTION_END_NUMBER, fid)
	}
	for _, fun := range allSupportedFunctions {
		check(fun.functionId)
	}

	for _, fid := range functionIdRegister {
		check(int(fid))
	}
}
