header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Matrix Origin
  paths:
    - '**/*.go'
    - '**/*.c'
    - '**/*.s'
    - '**/*.h'
    - '**/*.cpp'
    - '**/*.proto'
  paths-ignore:
    - 'docs/'
    - 'test/'
    - 'optools/'
    - 'cgo/external/'
    - 'pkg/frontend/test/'
    - 'pkg/vm/engine/tae/mergesort/*/sort.go'
    - '**/.gitignore'
    - '**/goyacc.go'
  comment: on-failure