header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Matrix Origin
  paths:
    - '**/*.go'
    - '**/*.c'
    - '**/*.s'
    - '**/*.h'
    - '**/*.cpp'
    - '**/*.proto'
  paths-ignore:
    - 'docs/'
    - 'test/'
    - 'optools/'
    - 'cgo/external/'
    - 'pkg/frontend/test/'
    - 'pkg/vm/engine/tae/mergesort/sort.go'
    - 'pkg/vm/engine/tae/mergesort/heap.go'
    - 'pkg/hakeeper/operator/'
    - '**/*.pb.go'
    - '**/.gitignore'
    - '**/goyacc.go'
    - 'pkg/sql/parsers/dialect/postgresql/postgresql_sql.go'
    - 'pkg/sql/parsers/dialect/mysql/mysql_sql.go'
  comment: on-failure
dependency:
  files:
    - go.mod
