header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Matrix Origin
  paths:
    - '**/*.go'
    - '**/*.c'
    - '**/*.s'
    - '**/*.h'
    - '**/*.cpp'
    - '**/*.proto'
  paths-ignore:
    - 'docs/'
    - 'test/'
    - 'optools/'
    - 'cgo/external/'
    - 'thirdparties/'
    - 'pkg/frontend/test/'
    - 'pkg/vm/engine/tae/mergesort/sort.go'
    - 'pkg/vm/engine/tae/mergesort/heap.go'
    - 'pkg/hakeeper/operator/'
    - '**/*.pb.go'
    - '**/.gitignore'
    - '**/goyacc.go'
    - 'pkg/sql/parsers/dialect/postgresql/postgresql_sql.go'
    - 'pkg/sql/parsers/dialect/mysql/mysql_sql.go'
    - 'pkg/common/fastrand/'
    - 'pkg/common/arenaskl/'
    - 'pkg/common/malloc/mimalloc/'
  comment: on-failure
dependency:
  files:
    - go.mod
  licenses:
    - name: github.com/mattn/go-localereader
      license: MIT
    # The generated Go submodule carries Apache-2.0 SPDX headers but omits
    # the repository-level LICENSE file from its module zip.
    - name: github.com/substrait-io/substrait-protobuf/go
      license: Apache-2.0
