create sequence alter_seq_01 as smallint increment by 2 minvalue 30 maxvalue 100 cycle;
select * from alter_seq_01;
alter sequence alter_seq_02 no cycle;
alter sequence alter_seq_01 no cycle;
select * from alter_seq_01;
alter sequence alter_seq_01 as bigint;
select * from alter_seq_01;
alter sequence alter_seq_01 as tinyint;
select * from alter_seq_01;
alter sequence alter_seq_01 increment by 3;
select * from alter_seq_01;
alter sequence alter_seq_01 start with 40;
select * from alter_seq_01;
alter sequence alter_seq_01 minvalue 10;
select * from alter_seq_01;
alter sequence alter_seq_01 maxvalue 1000;
select * from alter_seq_01;
alter sequence alter_seq_01 minvalue 10000 maxvalue 10;
alter sequence alter_seq_01 minvalue 1 maxvalue 1000000000 cycle;
select * from alter_seq_01;
drop sequence alter_seq_01;