set enable_remap_hint = 1;
create database if not exists db1;
create database if not exists db2;
create table db1.t1 (a int, b int, c int);
insert into db1.t1 values(1, 2, 3), (4, 5, 6), (7, 8, 9);
create table db2.t1 (a int, b int, c int);
insert into db2.t1 values(1, 2, 3), (4, 5, 6), (7, 8, 9);
use db1;
/*+ { "rewrites" : { "db1.t1": "select a from db1.t1" } } */ Select * from t1;
/*+ { "rewrites" : { "db1.t1": "select sum(a) as sb from db1.t1" } } */ Select l.sb from db1.t1 as l;
/*+ { "rewrites" : { "db1.t1": "select a from db1.t1" } } */ Select * from db1.t1;
/*+ { "rewrites" : { "db2.t1": "select a from db2.t1" } } */ Select * from db1.t1;
/*+ { "rewrites" : { "db1.t1": "select a from db1.t1" } } */ Select db1.t1.c from db1.t1;
/*+ { "rewrites" : { "db1.t1": "select a from db1.t1" } } */ Select db1.t1.a from db1.t1;
/*+ {"rewrites": {"db1.t1":"(select a,b from db1.t1 where a>1)","db2.t1":"(select a,c from db2.t1 where c<9)"}} */ select l.a,r.c from db1.t1 l join db2.t1 r on l.a=r.a;
/*+ {"rewrites": {"db1.t1":"(select a,b*10 as b,c from db1.t1)","db2.t1":"(select a,b,c from db2.t1)"}} */ select l.a,l.b,r.c from db1.t1 l join db2.t1 r on l.a=r.a;
/*+ {"rewrites": {"db1.t1":"(select a from db1.t1 where a<=4)","db2.t1":"(select a,b from db2.t1)"}} */ select l.a,r.b from db1.t1 l left join db2.t1 r on l.a=r.a where r.b is not null;
drop database if exists db1;
drop database if exists db2;
set enable_remap_hint = 0;