service-type = "CN"
data-dir = "./mo-data"

[log]
level = "info"
format = "console"
max-size = 512

[hakeeper-client]
service-addresses = [
  "172.19.0.4:32001",
]

[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "S3"
backend = "DISK"
data-dir = "mo-data/s3"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"

[observability]
disableTrace = true
disableMetric = true

[cn]
uuid = "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"
listen-address = "0.0.0.0:6002"
service-address = "172.19.0.2:6002"
sql-address = "172.19.0.2:6001"

[cn.Engine]
type = "distributed-tae"
