# service node type, [DN|CN|LOG]
service-type = "CN"
data-dir = "./mo-data"

[log]
level = "debug"
format = "json"
max-size = 512


[hakeeper-client]
service-addresses = [
    "127.0.0.1:32001",
]

[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "S3"
backend = "MEM"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"

[cn]
uuid = "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"
listen-address = "127.0.0.1:3307"
role = "TP"

[cn.Engine]
type = "tae"
logstore = "logservice"

[observability]
statusPort = 9001
