-- @skip:issue#7889
drop database if exists test_temporary;
create database test_temporary;
use test_temporary;
create temporary table t (a int);
create table t1 (a int);
-- test Temporary tables are not displayed when show table
show tables;
insert into t values (1), (2), (3);
select * from t;
delete from t where a = 1;
select * from t;
update t set a = 4 where a = 3;
select * from t;
insert into t1 values (100);
insert into t select * from t1;
select * from t;
drop database if exists test_temporary2;
create database test_temporary2;
use test_temporary2;
create temporary table t (a int);
create table t1 (a int);
select * from t;
drop table t;
select * from test_temporary.t;
drop database if exists test_temporary;
drop database if exists test_temporary2;
drop database if exists test_tmp;
create database test_tmp;
use test_tmp;
drop table if exists f1;
drop table if exists t1;
create table f1 (a int primary key);
create temporary table  t1 (a int primary key);
create temporary table c1(a int, constraint ck foreign key(a) REFERENCES f1(a));
create table c1(a int, constraint ck foreign key(a) REFERENCES t1(a));
drop table if exists f1;
drop table if exists t1;
drop database if exists test_tmp;