logservices = [
    "./etc/launch-tae-multi-CN-tae-DN/log.toml",
]

dnservices = [
    "./etc/launch-tae-multi-CN-tae-DN/dn.toml"
]

cnservices = [
    "./etc/launch-tae-multi-CN-tae-DN/cn1.toml",
    "./etc/launch-tae-multi-CN-tae-DN/cn2.toml"
]
