version: '3.9'

services:
  cn-0:
    container_name: cn-0
    build:
      context: ../../
      dockerfile: ./optools/images/Dockerfile
      args:
        GOPROXY: "https://proxy.golang.com.cn,direct"
    image: matrixorigin/matrixone:nightly-b9c225f4
    entrypoint: ["/mo-service", "-cfg", "/config/cn-0.toml"]
    depends_on:
      - dn
    ports:
      - "6001:6001"
      - "6002"
    restart: on-failure
    volumes:
      - ../../etc/launch-mo-compose-local/config:/config
    tty: true
    networks:
      monet:

  dn:
    container_name: dn
    build:
      context: ../../
      dockerfile: ./optools/images/Dockerfile
      args:
        GOPROXY: "https://proxy.golang.com.cn,direct"
    image: matrixorigin/matrixone:nightly-b9c225f4
    entrypoint: ["/mo-service", "-cfg", "/config/dn.toml"]
    depends_on:
      - logservice
    ports:
      - "41010"
    restart: on-failure
    tty: true
    volumes:
      - ../../etc/launch-mo-compose-local/config:/config
    networks:
      monet:

  logservice:
    container_name: logservice
    build:
      context: ../../
      dockerfile: ./optools/images/Dockerfile
      args:
        GOPROXY: "https://proxy.golang.com.cn,direct"
    image: matrixorigin/matrixone:nightly-b9c225f4
    entrypoint: ["/mo-service", "-cfg", "/config/log.toml"]
    ports:
      - "32000"
      - "32001"
      - "32002"
    restart: on-failure
    volumes:
      - ../../etc/launch-mo-compose-local/config:/config
    tty: true    
    networks:
      monet:
        ipv4_address: 179.19.0.4

networks:
  monet:
    driver: bridge
    ipam:
      config:
        - subnet: 179.19.0.0/16