# service node type, [DN|CN|LOG]
service-type = "CN"

[log]
level = "debug"
format = "json"
max-size = 512


[hakeeper-client]
service-addresses = [
    "127.0.0.1:32001",
    "127.0.0.1:32011",
    "127.0.0.1:32021",
]

[[fileservice]]
name = "LOCAL"
backend = "MEM"

[[fileservice]]
name = "S3"
backend = "MEM"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"
data-dir = "store"

[cn]
uuid = "dd1dccb4-4d3c-41f8-b483-5351dc7a41bf"
listen-address = "127.0.0.1:6002"
role = "TP"

[cn.Engine]
type = "memory"

[cn.frontend]
port = 6002

[observability]
statusPort = 9002
