apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: mo-checkin-regression
  namespace: nsformocheckin
spec:
  nodeSelector:
    role: mo-big-data-pr
  dn:
    overlay:
      imagePullSecrets:
      - name: dockerhub
    cacheVolume:
      size: 100Gi
      storageClassName: gp3
    sharedStorageCache:
      memoryCacheSize: 1Gi
      diskCacheSize: 100Gi
    config: |
      [dn.Txn.Storage]
      backend = "TAE"
      log-backend = "logservice"
      [dn.Ckp]
      flush-interval = "60s"
      min-count = 100
      scan-interval = "5s"
      incremental-interval = "60s"
      global-interval = "100000s"
      [dn.LogtailServer]
      rpc-max-message-size = "16KiB"
      rpc-payload-copy-buffer-size = "16KiB"
      rpc-enable-checksum = true
      logtail-collect-interval = "2ms"
      logtail-response-send-timeout = "10s"
      max-logtail-fetch-failure = 5
    replicas: 1
    resources:
      requests:
        cpu: 3
        memory: 12Gi
      limits:
        cpu: 8
        memory: 16Gi
  imageRepository: matrixorigin/matrixone
  logService:
    overlay:
      imagePullSecrets:
      - name: dockerhub
    replicas: 3
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 8
        memory: 16Gi
    sharedStorage:
      s3:
        path: s3pathformocheckin
        s3RetentionPolicy: Retain
        secretRef:
          name: aws-secret
    pvcRetentionPolicy: Delete
    volume:
      size: 100Gi
      storageClassName: gp3
    config: |
      [log]
      level = "info"
      format = "json"
      max-size = 512
  tp:
    cacheVolume:
      size: 100Gi
      storageClassName: gp3
    sharedStorageCache:
      memoryCacheSize: 1Gi
      diskCacheSize: 100Gi
    config: |
      [cn.Engine]
      type = "distributed-tae"
      [log]
      level = "info"
      format = "json"
      max-size = 512
      [cn.rpc]
      send-queue-size = 2
      busy-queue-size = 1
      [cn.txn]
      enable-sacrificing-freshness = true
      enable-cn-based-consistency = false
      [cn.ctl.address]
      listen-address = "0.0.0.0:19958"
    replicas: 2
    overlay:
      imagePullSecrets:
      - name: dockerhub
      env:
      - name: GOMEMLIMIT
        value: "10000MiB"
    resources:
      requests:
        cpu: 6
        memory: 16Gi
      limits:
        cpu: 8
        memory: 16Gi
  version: imagetag
