name: Bug report
description: Create a bug report to improve MatrixOne
title: "[Bug]: "
labels: [kind/bug, needs-triage]
assignees:
  - matrix-meow
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for the same bug?
      description: Please check if an issue already exists for the bug you encountered.
      options:
        - label: I have checked the existing issues.
          required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Enter the Environment Details:
      value: |
        - Version or commit-id (e.g. v0.1.0 or 8b23a93):
        - Hardware parameters:
        - OS type:
        - Others:
      render: Markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Actual Behavior
      description: Describe what you encountered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expected.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce what you encountered.
      render: Markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Log, error message or any other information can help find the root cause.
    validations:
      required: false
