name: Tech request
description: As a developer, I would like to suggest a tech idea for MatrixOne.
title: "[Tech Request]: "
# labels: [kind/tech-request, needs-triage]
labels: [kind/tech-request]
# assignees:
#   - m-schen
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for the same tech request?
      description: Please check if an issue already exists for the tech request issue.
      options:
        - label: I have checked the existing issues.
          required: true
  - type: checkboxes
    attributes:
      label: Does this tech request not affect user experience?
      description: If yes, please submit a feature request issue.
      options:
        - label: This tech request doesn't affect user experience.
          required: true
  - type: textarea
    attributes:
      label: What would you like to be added ?
      description: |
        A concise description of what you're expecting/suggesting.
      render: Markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why is this needed ?
      description: A concise description of the reason/motivation.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Add any other context or screenshots about the request here.
    validations:
      required: false
