name: Feature request
description: Suggest an idea for MatrixOne
title: "[Feature Request]: "
labels: [kind/feature, needs-triage]
assignees:
  - m-schen
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for the same bug?
      description: Please check if an issue already exists for the bug you encountered.
      options:
        - label: I have checked the existing issues.
          required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? 
      description: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Documentation, Adoption, Use Case, Migration Strategy
      description: If you can, explain some scenarios how users might use this, situations it would be helpful in. Any API designs, mockups, or diagrams are also helpful. 
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Add any other context or screenshots about the feature request here.
    validations:
      required: false
