name: Performance question
description: Create a performance problem report to improve MatrixOne
title: "[Performance]: "
# labels: [kind/performance, needs-triage]
labels: [kind/performance]
# assignees:
#   - m-schen
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for performance?
      description: Please check if an issue already exists for the performance issue you encountered.
      options:
        - label: I have checked the existing issues.
          required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Enter the Environment Details:
      value: |
        - Version or commit-id (e.g. v0.1.0 or 8b23a93):
        - Hardware parameters:
        - OS type:
        - Others:
      render: Markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Details of Performance
      description: |
        Please describe the details of your desired performance requirements.
      value: |
        For example:Do you want to improve the response time? 
        Or the number of concurrent requests? Or is the throughput?
    validations:
      required: true
  # - type: textarea
  #   attributes:
  #     label: Actual Behavior
  #     description: Describe the performance what you encountered.
  #   validations:
  #     required: true
  # - type: textarea
  #   attributes:
  #     label: Expected Behavior
  #     description: Describe the performance what you expected.
  #   validations:
  #     required: false
  # - type: textarea
  #   attributes:
  #     label: Steps to Reproduce
  #     description: List steps detailedly to reproduce the operations to test performance.
  #     render: markdown
  #   validations:
  #     required: false
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Add any other context about the problem here.
      value: |
        For example: Have you compared MatrixOne with other databases? 
        If yes, what's their difference?
    validations:
      required: false
