name: Refactoring request
description: Make a refactoring request to MatrixOne
title: "[Refactoring]: "
# labels: [kind/refactoring, needs-triage]
labels: [kind/refactoring]
# assignees:
#   - m-schen
body:
  # - type: checkboxes
  #   attributes:
  #     label: Is there an existing issue for the refactoring request?
  #     description: Please check if an issue already exists for the issue you encountered.
  #     options:
  #       - label: I have checked the existing issues.
  #         required: true
  - type: textarea
    attributes:
      label: Why do you want to refactor this code?
      description: |
        A clear and concise description of the refactoring you want to.
      render: Markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or refactoring method you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Add any other context or screenshots about the refactoring request here.
    validations:
      required: false
