# service node type, [DN|CN|LOG]
service-type = "DN"

[log]
level = "debug"
format = "json"
max-size = 512

[hakeeper-client]
service-addresses = [
    "1",
    "2"
]

[[fileservice]]
# s3 fileservice instance, used to store data.
name = "SHARED"
# use s3 as fileservice backend.
backend = "S3"
[fileservice.s3]
endpoint = "s3 endpoint"
bucket = "s3 bucket"
key-prefix = "s3 key preifx"

[dn]
uuid = "dn uuid"

[dn.Txn.Storage]
# txn storage backend implementation. [TAE|MEM]
backend = "MEM"

