drop database if exists test_temporary;
create database test_temporary;
use test_temporary;
create temporary table t (a int);
create table t1 (a int);
show tables;
insert into t values (1), (2), (3);
select * from t;
delete from t where a = 1;
select * from t;
update t set a = 4 where a = 3;
select * from t;