drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
drop database if exists T;
create database T;
use T;
drop table IF EXISTS A;
create table A(a int);
insert into A values (1),(2),(3),(4),(5);
insert into A values (1),(2),(3),(4),(5);
