service-type = "DN"

[log]
level = "debug"
format = "console"
max-size = 512

[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "S3"
backend = "DISK"
data-dir = "mo-data/s3"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"

[hakeeper-client]
service-addresses = ["logservice-0:32001"]

[dn]
uuid = "713F97B0-1E28-4F80-849D-FE0979AE734A"
service-address = "dn:41010"
listen-address = "0.0.0.0:41010"

[dn.Txn]

[dn.Txn.Storage]
backend = "TAE"
log-backend = "logservice"

[dn.Ckp]
flush-interval = "60s"
min-count = 100
scan-interval = "5s"
incremental-interval = "180s"
global-interval = "100000s"
