-- @suit
-- @case
-- @desc:test for BIT_COUNT() (MySQL compatible: returns number of set bits)
-- @label:bvt

SELECT BIT_COUNT(0);
SELECT BIT_COUNT(1);
SELECT BIT_COUNT(3);
SELECT BIT_COUNT(255);
SELECT BIT_COUNT(256);
SELECT BIT_COUNT(-1);

DROP TABLE IF EXISTS t;
CREATE TABLE t(
	tiny TINYINT NOT NULL,
	small SMALLINT NOT NULL,
	int_t INT NOT NULL,
	big BIGINT NOT NULL
);
INSERT INTO t VALUES (0, 1, 3, 255);
INSERT INTO t VALUES (127, 32767, 65535, 9223372036854775807);
SELECT BIT_COUNT(tiny), BIT_COUNT(small), BIT_COUNT(int_t), BIT_COUNT(big) FROM t;

DROP TABLE IF EXISTS t;
CREATE TABLE t(
	tiny TINYINT UNSIGNED NOT NULL,
	small SMALLINT UNSIGNED NOT NULL,
	int_t INT UNSIGNED NOT NULL,
	big BIGINT UNSIGNED NOT NULL
);
INSERT INTO t VALUES (255, 65535, 65535, 18446744073709551615);
SELECT BIT_COUNT(tiny), BIT_COUNT(small), BIT_COUNT(int_t), BIT_COUNT(big) FROM t;
