#like
select 'ab' like '__' as result;
select 'ab' like '_%' as result;
select 'ab' like '%' as result;
select 'ab' like 'a_' as result;
select 'ab' like '_b' as result;
select 'ab' like '%' as result;
select 'ab' like '*' as result;
select '*' like '*' as result;
select '**' like '**' as result;
select '**' like '*_' as result;
select '**' like '*^' as result;
select '(_a)' like '(_a)';
drop table if exists t1;
create table t1(a int, b varchar(100));
insert into t1 values(1 , "PowerSlave");
insert into t1 values(2 , "Powerage");
insert into t1 values( 3 , "Singing Down the Lane" );
insert into t1 values(4 , "Ziltoid the Omniscient");
insert into t1 values(5 , "Casualties of Cool");
insert into t1 values( 6 , "Epicloud");
insert into t1 values(7 , "Somewhere in Time");
insert into t1 values(8 , "Piece of Mind");
insert into t1 values( 9 , "Killers");
insert into t1 values(10 , "No Prayer for the Dying");
insert into t1 values(11 , "No Sound Without Silence");
insert into t1 values(12 , "Big Swing Face");
insert into t1 values(13 , "Blue Night");
insert into t1 values(14 , "Eternity");
insert into t1 values(15 , "Scandinavia");
insert into t1 values(16 , "Long Lost Suitcase");
insert into t1 values(17 , "Praise and Blame");
insert into t1 values(18 , "Along Came Jones");
insert into t1 values(19 , "All Night Wrong");
insert into t1 values(20 , "The Sixteen Men of Tain");
SELECT a, b
FROM t1
WHERE b like 'Power%';
drop table t1;
create table t1 (str1 varchar(25),str2 char(25));
insert into t1 values('a1','b1'),('a2', 'b2'),('%str1%', '%str2%');
select * from t1 where str1 like "%\%";
select * from t1 where str1 like "\%%";

select json_extract('{"a":1}', '$.a') like '1' as result;
select json_extract('{"a":1}', '$.a') like 1 as result;
select json_extract('{"a":"1"}', '$.a') like '1' as result;
select json_extract('{"a":"1"}', '$.a') like 1 as result;
select json_extract('{"a":"1"}', '$.a') like '%1%' as result;
select json_unquote(json_extract('{"a":"1"}', '$.a')) like '1' as result;
select json_unquote(json_extract('{"a":"1"}', '$.a')) like 1 as result;