select instr('aaa','a');
select instr('aaa','ax');
select instr('aaa','aa');
select instr('aaa',1);
select instr('aaa','b');
select instr(null,'a');
select instr(1,null);
select instr(null,null);
select instr(null,'a');
select instr('','啊');
select instr('','a');
select instr('',' ');
select instr('','');
select instr('啊','');
select instr('啊',' ');
select instr('啊','啊');
select instr('x啊','啊');
select instr('x啊啦啦啦啦啦的','啦');
select instr('x啊啦啦啦啦啦的q','的');
select instr('x啊啦啦啦啦啦的q','q');
create table t1(a varchar,b varchar);
insert into t1 values('axa','x'),('abababa','qq'),('qwer','er');
select instr(a,b) from t1;
select instr(a,null) from t1;
select instr(null,b) from t1;
select instr('axa','x') from t1;
select instr(a,'qw') from t1;
select instr('qwer',b) from t1;
insert into t1 values('','啊'),('','a'),('',' '),('',''),('啊',''),('啊',' '),('啊','啊'),('x啊','啊'),('x啊啦啦啦啦啦的','啦'),('x啊啦啦啦啦啦的q','的'),('x啊啦啦啦啦啦的q','q');
select instr(a,b) from t1;