-- CTAS must apply the session division policy while populating the table.
-- Related to #28605. Three source rows prove partial results are not retained.
DROP DATABASE IF EXISTS div_zero_ctas;
CREATE DATABASE div_zero_ctas;
USE div_zero_ctas;
SET @saved_sql_mode = @@SESSION.sql_mode;
CREATE TABLE src(id INT PRIMARY KEY, n INT, d INT);
INSERT INTO src VALUES (1,10,2),(2,10,0),(3,9,3);
SET SESSION sql_mode = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO';
SELECT 10/0 AS v;
SELECT id,n/d AS v FROM src ORDER BY id;
-- CTAS: runtime arithmetic, constant folding, and SQL spellings.
CREATE TABLE copied AS SELECT id,n/d AS v FROM src ORDER BY id;
SELECT * FROM copied;
CREATE TABLE copied(marker INT);
DROP TABLE copied;
CREATE TABLE constant AS SELECT 10/0 AS v;
SELECT * FROM constant;
CREATE TABLE constant(marker INT);
DROP TABLE constant;
CREATE TABLE decimal_result AS SELECT CAST(n AS DECIMAL(18,4))/d AS v FROM src;
SELECT * FROM decimal_result;
CREATE TABLE decimal_result(marker INT);
DROP TABLE decimal_result;
CREATE TABLE float_result AS SELECT CAST(n AS DOUBLE)/d AS v FROM src;
SELECT * FROM float_result;
CREATE TABLE float_result(marker INT);
DROP TABLE float_result;
CREATE TABLE intdiv AS SELECT n DIV d AS v FROM src;
SELECT * FROM intdiv;
CREATE TABLE intdiv(marker INT);
DROP TABLE intdiv;
CREATE TABLE modulo AS SELECT n % d AS v FROM src;
SELECT * FROM modulo;
CREATE TABLE modulo(marker INT);
DROP TABLE modulo;
CREATE TABLE modfunc AS SELECT MOD(n,d) AS v FROM src;
SELECT * FROM modfunc;
CREATE TABLE modfunc(marker INT);
DROP TABLE modfunc;
CREATE TABLE unioned AS SELECT n/d AS v FROM src UNION ALL SELECT 1;
SELECT * FROM unioned;
CREATE TABLE unioned(marker INT);
DROP TABLE unioned;
CREATE TABLE derived AS SELECT v FROM (SELECT n/d AS v FROM src) q;
SELECT * FROM derived;
CREATE TABLE derived(marker INT);
DROP TABLE derived;
CREATE TABLE explicit_cols(v DOUBLE) SELECT n/d FROM src;
SELECT * FROM explicit_cols;
CREATE TABLE explicit_cols(marker INT);
DROP TABLE explicit_cols;
CREATE TABLE safe AS SELECT id,n/NULLIF(d,0) AS v FROM src ORDER BY id;
SELECT id,v,v IS NULL AS is_null FROM safe ORDER BY id;
DROP TABLE safe;
CREATE TABLE empty_result AS SELECT n/d AS v FROM src WHERE id < 0;
SELECT COUNT(*) FROM empty_result;
DROP TABLE empty_result;
CREATE TABLE ignored IGNORE AS SELECT id,n/d AS v FROM src ORDER BY id;
SELECT id,v,v IS NULL AS is_null FROM ignored ORDER BY id;
DROP TABLE ignored;
CREATE TABLE replaced REPLACE AS SELECT n/d AS v FROM src;
SELECT * FROM replaced;
-- TEMPORARY CTAS: runtime arithmetic, constant folding, and SQL spellings.
CREATE TEMPORARY TABLE copied AS SELECT id,n/d AS v FROM src ORDER BY id;
SELECT * FROM copied;
CREATE TEMPORARY TABLE copied(marker INT);
DROP TABLE copied;
CREATE TEMPORARY TABLE constant AS SELECT 10/0 AS v;
SELECT * FROM constant;
CREATE TEMPORARY TABLE constant(marker INT);
DROP TABLE constant;
CREATE TEMPORARY TABLE decimal_result AS SELECT CAST(n AS DECIMAL(18,4))/d AS v FROM src;
SELECT * FROM decimal_result;
CREATE TEMPORARY TABLE decimal_result(marker INT);
DROP TABLE decimal_result;
CREATE TEMPORARY TABLE float_result AS SELECT CAST(n AS DOUBLE)/d AS v FROM src;
SELECT * FROM float_result;
CREATE TEMPORARY TABLE float_result(marker INT);
DROP TABLE float_result;
CREATE TEMPORARY TABLE intdiv AS SELECT n DIV d AS v FROM src;
SELECT * FROM intdiv;
CREATE TEMPORARY TABLE intdiv(marker INT);
DROP TABLE intdiv;
CREATE TEMPORARY TABLE modulo AS SELECT n % d AS v FROM src;
SELECT * FROM modulo;
CREATE TEMPORARY TABLE modulo(marker INT);
DROP TABLE modulo;
CREATE TEMPORARY TABLE modfunc AS SELECT MOD(n,d) AS v FROM src;
SELECT * FROM modfunc;
CREATE TEMPORARY TABLE modfunc(marker INT);
DROP TABLE modfunc;
CREATE TEMPORARY TABLE unioned AS SELECT n/d AS v FROM src UNION ALL SELECT 1;
SELECT * FROM unioned;
CREATE TEMPORARY TABLE unioned(marker INT);
DROP TABLE unioned;
CREATE TEMPORARY TABLE derived AS SELECT v FROM (SELECT n/d AS v FROM src) q;
SELECT * FROM derived;
CREATE TEMPORARY TABLE derived(marker INT);
DROP TABLE derived;
CREATE TEMPORARY TABLE explicit_cols(v DOUBLE) SELECT n/d FROM src;
SELECT * FROM explicit_cols;
CREATE TEMPORARY TABLE explicit_cols(marker INT);
DROP TABLE explicit_cols;
CREATE TEMPORARY TABLE safe AS SELECT id,n/NULLIF(d,0) AS v FROM src ORDER BY id;
SELECT id,v,v IS NULL AS is_null FROM safe ORDER BY id;
DROP TABLE safe;
CREATE TEMPORARY TABLE empty_result AS SELECT n/d AS v FROM src WHERE id < 0;
SELECT COUNT(*) FROM empty_result;
DROP TABLE empty_result;
CREATE TEMPORARY TABLE ignored IGNORE AS SELECT id,n/d AS v FROM src ORDER BY id;
SELECT id,v,v IS NULL AS is_null FROM ignored ORDER BY id;
DROP TABLE ignored;
CREATE TEMPORARY TABLE replaced REPLACE AS SELECT n/d AS v FROM src;
SELECT * FROM replaced;
-- Without both mode flags, all three rows must be materialized.
SET SESSION sql_mode = 'STRICT_TRANS_TABLES';
CREATE TABLE allowed AS SELECT id,n/d AS v,n DIV d AS q,n % d AS r FROM src ORDER BY id;
SELECT id,v,q,r,v IS NULL AS is_null FROM allowed ORDER BY id;
DROP TABLE allowed;
CREATE TEMPORARY TABLE allowed AS SELECT id,n/d AS v,n DIV d AS q,n % d AS r FROM src ORDER BY id;
SELECT id,v,q,r,v IS NULL AS is_null FROM allowed ORDER BY id;
DROP TABLE allowed;
SET SESSION sql_mode = 'STRICT_ALL_TABLES';
CREATE TABLE allowed AS SELECT id,n/d AS v,n DIV d AS q,n % d AS r FROM src ORDER BY id;
SELECT id,v,q,r,v IS NULL AS is_null FROM allowed ORDER BY id;
DROP TABLE allowed;
CREATE TEMPORARY TABLE allowed AS SELECT id,n/d AS v,n DIV d AS q,n % d AS r FROM src ORDER BY id;
SELECT id,v,q,r,v IS NULL AS is_null FROM allowed ORDER BY id;
DROP TABLE allowed;
SET SESSION sql_mode = 'ERROR_FOR_DIVISION_BY_ZERO';
CREATE TABLE allowed AS SELECT id,n/d AS v,n DIV d AS q,n % d AS r FROM src ORDER BY id;
SELECT id,v,q,r,v IS NULL AS is_null FROM allowed ORDER BY id;
DROP TABLE allowed;
CREATE TEMPORARY TABLE allowed AS SELECT id,n/d AS v,n DIV d AS q,n % d AS r FROM src ORDER BY id;
SELECT id,v,q,r,v IS NULL AS is_null FROM allowed ORDER BY id;
DROP TABLE allowed;
SET SESSION sql_mode = '';
CREATE TABLE allowed AS SELECT id,n/d AS v,n DIV d AS q,n % d AS r FROM src ORDER BY id;
SELECT id,v,q,r,v IS NULL AS is_null FROM allowed ORDER BY id;
DROP TABLE allowed;
CREATE TEMPORARY TABLE allowed AS SELECT id,n/d AS v,n DIV d AS q,n % d AS r FROM src ORDER BY id;
SELECT id,v,q,r,v IS NULL AS is_null FROM allowed ORDER BY id;
DROP TABLE allowed;
SET SESSION sql_mode = 'STRICT_ALL_TABLES,ERROR_FOR_DIVISION_BY_ZERO';
CREATE TABLE all_strict AS SELECT n/d AS v FROM src;
SELECT * FROM all_strict;
SET SESSION sql_mode = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO';
-- DML controls: rejected statements must preserve existing rows.
CREATE TABLE target(id INT PRIMARY KEY,v DOUBLE);
INSERT INTO target SELECT id,n/d FROM src ORDER BY id;
SELECT COUNT(*) FROM target;
INSERT INTO target VALUES (1,7);
UPDATE target SET v=10/0 WHERE id=1;
SELECT * FROM target;
PREPARE p FROM 'INSERT INTO target VALUES(?,10/0)';
SET @id = 2;
EXECUTE p USING @id;
DEALLOCATE PREPARE p;
SELECT * FROM target;
-- Prepared CTAS must recompute the policy at each execution.
PREPARE ctas FROM 'CREATE TABLE prepared AS SELECT n/d AS v FROM src';
EXECUTE ctas;
SELECT * FROM prepared;
SET SESSION sql_mode = 'STRICT_TRANS_TABLES';
EXECUTE ctas;
SELECT v,v IS NULL AS is_null FROM prepared ORDER BY v;
DROP TABLE prepared;
SET SESSION sql_mode = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO';
EXECUTE ctas;
SELECT * FROM prepared;
DEALLOCATE PREPARE ctas;
PREPARE temp_ctas FROM 'CREATE TEMPORARY TABLE prepared_tmp AS SELECT id,n/d AS v FROM src ORDER BY id';
EXECUTE temp_ctas;
SELECT * FROM prepared_tmp;
SET SESSION sql_mode = 'STRICT_TRANS_TABLES';
EXECUTE temp_ctas;
SELECT id,v,v IS NULL AS is_null FROM prepared_tmp ORDER BY id;
DROP TABLE prepared_tmp;
SET SESSION sql_mode = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO';
EXECUTE temp_ctas;
SELECT * FROM prepared_tmp;
DEALLOCATE PREPARE temp_ctas;
-- Failure leaves no target within or after an explicit transaction.
BEGIN;
CREATE TABLE txn_failed AS SELECT id,n/d AS v FROM src ORDER BY id;
SELECT * FROM txn_failed;
ROLLBACK;
SELECT * FROM txn_failed;
SELECT * FROM target;
SELECT id,n,d FROM src ORDER BY id;
SELECT 10/0 AS v;
SET SESSION sql_mode = @saved_sql_mode;
DROP DATABASE div_zero_ctas;
