SELECT REGEXP_REPLACE('Cat Dog Cat Dog Cat','Cat', 'Tiger') 'Result';
SELECT REGEXP_REPLACE('Cat Dog Cat Dog Cat', 'Cow', 'Tiger') 'Result';
SELECT REGEXP_REPLACE('Cat Dog Cat Dog Cat', 'Cat', 'Tiger', 1, 2) 'Result';
SELECT REGEXP_REPLACE('Cat Dog Cat Dog Cat', 'Cat', 'Tiger', 2, 1) 'Result';
SELECT REGEXP_REPLACE('Cat Dog Cat Dog Cat', 'Cat', 'Tiger', 2, 2) 'Result';
SELECT REGEXP_REPLACE('Cat Dog Cat Dog Cat', 'Cat', 'Tiger', 1, 0) 'Result';
SELECT REGEXP_REPLACE(NULL, 'Cow', 'Tiger');
SELECT REGEXP_REPLACE('Cat Dog Cat Dog Cat', NULL, 'Tiger');
SELECT REGEXP_REPLACE('Cat Dog Cat Dog Cat', 'Cow', NULL);

create table t1(a int, b varchar(100));
insert into t1 values(1 , 'Cat Dog Cat Dog Cat Cat Dog Cat Dog Cat');
insert into t1 values(2 , 'Cat Dog Cat Dog Cat Cat Dog Cat Dog Cat');
insert into t1 values(3 , 'Cat Dog Cat Dog Cat Cat Dog Cat Dog Cat');
insert into t1 values(4 , 'Cat Dog Cat Dog Cat Cat Dog Cat Dog Cat');
insert into t1 values(5 , 'Dog Cat Dog Cat Cat Dog Cat Dog Cat Cat');
insert into t1 values(6 , 'Dog Cat Dog Cat Cat Dog Cat Dog Cat Cat');
insert into t1 values(7 , 'Dog Cat Dog Cat Cat Dog Cat Dog Cat Cat');
insert into t1 values(8 , 'Dog Cat Dog Cat Cat Dog Cat Dog Cat Cat');
SELECT a, REGEXP_REPLACE(b, 'Cat', 'tiger') from t1;
drop table t1;

create table t1(a int, b varchar(100));
insert into t1 values(1 , 'Cat Dog Cat Dog Cat Cat Dog Cat Dog Cat');
insert into t1 values(2 , 'Cat Dog Cat Dog Cat Cat Dog Cat Dog Cat');
insert into t1 values(3 , 'Cat Dog Cat Dog Cat Cat Dog Cat Dog Cat');
insert into t1 values(4 , 'Cat Dog Cat Dog Cat Cat Dog Cat Dog Cat');
insert into t1 values(5 , 'Dog Cat Dog Cat Cat Dog Cat Dog Cat Cat');
insert into t1 values(6 , 'Dog Cat Dog Cat Cat Dog Cat Dog Cat Cat');
insert into t1 values(7 , 'Dog Cat Dog Cat Cat Dog Cat Dog Cat Cat');
insert into t1 values(8 , 'Dog Cat Dog Cat Cat Dog Cat Dog Cat Cat');
SELECT a, REGEXP_REPLACE(b, 'Cat', 'pig', 3) from t1;
drop table t1;

create table t1(a int, b varchar(100));
insert into t1 values(1 , 'Cat Dog Cat Dog Cat Cat Dog Cat Dog Cat');
insert into t1 values(2 , 'Cat Dog Cat Dog Cat Cat Dog Cat Dog Cat');
insert into t1 values(3 , 'Cat Dog Cat Dog Cat Cat Dog Cat Dog Cat');
insert into t1 values(4 , 'Cat Dog Cat Dog Cat Cat Dog Cat Dog Cat');
insert into t1 values(5 , 'Dog Cat Dog Cat Cat Dog Cat Dog Cat Cat');
insert into t1 values(6 , 'Dog Cat Dog Cat Cat Dog Cat Dog Cat Cat');
insert into t1 values(7 , 'Dog Cat Dog Cat Cat Dog Cat Dog Cat Cat');
insert into t1 values(8 , 'Dog Cat Dog Cat Cat Dog Cat Dog Cat Cat');
SELECT a, REGEXP_REPLACE(b, 'Cat', 'taC', 3, 2) from t1;
drop table t1;

DROP TABLE IF EXISTS t;
CREATE TABLE t(str1 VARCHAR(20), str2 CHAR(20));
INSERT INTO t VALUES ('W * P', 'W + Z - O'), ('have has having', 'do does doing');
INSERT INTO t VALUES ('XV*XZ', 'PP-ZZ-DXA'), ('aa bbb cc ddd', 'k ii lll oooo');
SELECT REGEXP_REPLACE(str1, '*', 'i'), REGEXP_REPLACE(str2,'hav','hiv') FROM t;
drop table t;