drop table if exists t1;
create table t1(a int,b text,c text);
insert into t1 values(1,"a","bc"),(2,"ab","c"),(3,"aa","bb"),(3,"aa","bb");
select group_concat(distinct a,b,c separator '|') from t1;
select group_concat(distinct b,c separator '|') from t1 group by a;
select group_concat(distinct b,c separator '|') from t1;
set @@sql_mode = "STRICT_TRANS_TABLES";
select group_concat(distinct b,c separator '|'),a from t1;
select a,group_concat(distinct b,c separator '|') from t1;
select group_concat(distinct b,c separator '|'),avg(a) from t1;
select avg(a),group_concat(distinct b,c separator '|') from t1;
select group_concat(distinct b,c separator '|'),sum(a) from t1;
select sum(a),group_concat(distinct b,c separator '|') from t1;
select group_concat(distinct b,c separator '|'),a from t1 group by a;
select a,group_concat(distinct b,c separator '|') from t1 group by a;
select group_concat(distinct b,c separator '|'),avg(a) from t1 group by a;
select avg(a),group_concat(distinct b,c separator '|') from t1 group by a;
select group_concat(distinct b,c separator '|'),sum(a) from t1 group by a;
select sum(a),group_concat(distinct b,c separator '|') from t1 group by a;
drop table if exists t1;
create table t1(a int, b char(1));
insert into t1 values (1, 'a');
select group_concat(a) as bb, case b when 1 then '是' else '否' end aa from t1;
select group_concat(b) as bb, case a when 1 then '是' else '否' end aa from t1;
set @@sql_mode = "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION";