drop table if exists wf_nested_guard;
create table wf_nested_guard(id int primary key, amt int);
insert into wf_nested_guard values (1,10),(2,20);
select row_number() over (order by id) as rn, sum(amt) over () as total from wf_nested_guard order by id;
select row_number() over () as rn, sum(rn) over () from wf_nested_guard;
select row_number() over () as rn, sum(amt) over (partition by rn) from wf_nested_guard;
select row_number() over () as rn, sum(amt) over (order by rn) from wf_nested_guard;
select sum(row_number() over (order by id)) over () from wf_nested_guard;
select sum(amt) over (order by row_number() over (order by id)) from wf_nested_guard;
select group_concat(amt order by row_number() over ()) over () from wf_nested_guard;
select group_concat(amt order by amt) over () from wf_nested_guard;
select row_number() over (order by id), sum(amt) over () from wf_nested_guard order by id;
drop table wf_nested_guard;
