select split_part('axbxc','x',1);
select split_part('axbxcxd','x',2);
select split_part('axbxcxd','x',3);
select split_part('axbxcxd','xc',1);
select split_part('axbxcxd','xc',2);
select split_part('axbxcxd','xc',3);
select split_part('axbxcxd','asas',1);
select split_part('axbxcxd','asas',2);
select split_part(null,'asas',3);
select split_part('axbxcxd',null,3);
select split_part('axbxcxd','asas',null);
select split_part('axxx','x',1);
select split_part('axxx','x',2);
select split_part('axxx','x',0);
select split_part('axxx','x',-1);
create table t1(a varchar,b varchar,c int);
insert into t1 values('axbxc','x',1),('axbxcxd','x',2),('axbxcxd','x',3),('axbxcxd','xc',1),('axbxcxd','xc',2),('axbxcxd','xc',3),('axbxcxd','asas',1),('axbxcxd','asas',2),(null,'asas',3),('axbxcxd',null,3),('axbxcxd','asas',null),('axxx','x',1),('axxx','x',2);
select split_part(a,b,c) from t1;
insert into t1 values('axxx','x',0);
select split_part(a,b,c) from t1;
insert into t1 values('axxx','x',-1);
select split_part(a,b,c) from t1;