select * from metadata_scan('func_ts_to_time.no_exist_table', '*') g;
drop table if exists t;
create table t(a int, b varchar, c float, d decimal(10, 8), e float(5, 2));
insert into t values(1, null, 1.1, 1, 1.11);
insert into t values(2, "abc", 2.0, 2, 2.22);
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
select count(*) from t;
-- @ignore:0
select mo_ctl("dn", "flush", "func_ts_to_time.t");
select sleep(1);
select count(*) from metadata_scan("func_ts_to_time.t", "*")g where create_ts <= NOW();
select count(*) from metadata_scan("func_ts_to_time.t", "*")g where create_ts = "0-0";
select count(*) from metadata_scan("func_ts_to_time.t", "*")g where create_ts > 0;
select count(*) from metadata_scan("func_ts_to_time.t", "*")g where create_ts > 9.9;
select count(*) from metadata_scan("func_ts_to_time.t", "*")g where cast(create_ts as TIMESTAMP) <= NOW();
select count(*) from metadata_scan("func_ts_to_time.t", "*")g where ts_to_time(create_ts) <= NOW();
select count(*) from metadata_scan("func_ts_to_time.t", "*")g where ts_to_time(create_ts, 2) <= NOW();
select count(*) from metadata_scan("func_ts_to_time.t", "*")g where ts_to_time(1) <= NOW();
