select * from metadata_scan('table_func_metadata_scan_idx_tb.no_exist_table', '*') g;
drop table if exists t;
create table t(a int, b varchar, c float, d decimal(10, 8), e float(5, 2));
insert into t values(1, null, 1.1, 1, 1.11);
insert into t values(2, "abc", 2.0, 2, 2.22);
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
select count(*) from t;
-- @ignore:0
select mo_ctl("dn", "flush", "table_func_metadata_scan_idx_tb.t");
CREATE INDEX idx_a ON t(a);
select distinct(col_name) from metadata_scan("table_func_metadata_scan_idx_tb.t.?idx_a", "*")g;
CREATE INDEX idx_c_d ON t(c, d);
select distinct(col_name) from metadata_scan("table_func_metadata_scan_idx_tb.t.?idx_c_d", "*")g;
select distinct(col_name) from metadata_scan("table_func_metadata_scan_idx_tb.t.?idx_invalid", "*")g;
select distinct(col_name) from metadata_scan("table_func_metadata_scan_idx_tb.t.idx_invalid", "*")g;

select distinct(col_name) from metadata_scan("table_func_metadata_scan_idx_tb.t.?idx_invalid.#", "*")g;
select distinct(col_name) from metadata_scan("table_func_metadata_scan_idx_tb.t.?idx_a.#", "*")g;
select distinct(col_name) from metadata_scan("table_func_metadata_scan_idx_tb.t.#", "*")g;
delete from t where a = 1;
select count(*) from t;
select distinct(col_name) from metadata_scan("table_func_metadata_scan_idx_tb.t.#", "*")g;
select distinct(col_name) from metadata_scan("table_func_metadata_scan_idx_tb.t.?idx_a.#", "*")g;