-- Deterministic assignment ownership and typed temporal regression contracts.
SET @old_sql_mode = @@sql_mode;
SET @old_time_zone = @@time_zone;
SET @old_explicit_defaults = @@explicit_defaults_for_timestamp;
SET @old_lc_time_names = @@lc_time_names;
DROP DATABASE IF EXISTS temporal_28932;
CREATE DATABASE temporal_28932;
USE temporal_28932;
SET time_zone = '+00:00';
SET timestamp = 1704164645.123456;
SET explicit_defaults_for_timestamp = OFF;
CREATE TABLE legacy_ts (id INT PRIMARY KEY, ts TIMESTAMP(6) NOT NULL DEFAULT '2000-01-01 00:00:00');
INSERT INTO legacy_ts VALUES (1, NULL), (2, '2000-01-01 00:00:00');
SELECT id, ts FROM legacy_ts ORDER BY id;
SET @p = NULL;
PREPARE ts_update FROM 'UPDATE legacy_ts SET ts = ? WHERE id = 2';
EXECUTE ts_update USING @p;
SELECT ts FROM legacy_ts WHERE id = 2;
SET @p = '2001-02-03 04:05:06.654321';
EXECUTE ts_update USING @p;
SELECT ts FROM legacy_ts WHERE id = 2;
SET @p = NULL;
EXECUTE ts_update USING @p;
SELECT ts FROM legacy_ts WHERE id = 2;
SET explicit_defaults_for_timestamp = ON;
EXECUTE ts_update USING @p;
SET explicit_defaults_for_timestamp = OFF;
EXECUTE ts_update USING @p;
SELECT ts FROM legacy_ts WHERE id = 2;
DEALLOCATE PREPARE ts_update;
INSERT INTO legacy_ts SELECT 3, NULL;
INSERT INTO legacy_ts VALUES (1, NULL) ON DUPLICATE KEY UPDATE ts = NULL;
SELECT id, ts FROM legacy_ts ORDER BY id;
CREATE SEQUENCE rhs_once START WITH 1;
CREATE TABLE update_once (id INT PRIMARY KEY, n BIGINT, ts TIMESTAMP(6) NOT NULL DEFAULT '2000-01-01 00:00:00' ON UPDATE CURRENT_TIMESTAMP(6));
INSERT INTO update_once VALUES (1, 1, '2000-01-01 00:00:00');
UPDATE update_once SET n = NEXTVAL('rhs_once') WHERE id = 1;
SELECT n, ts, CURRVAL('rhs_once') AS consumed FROM update_once;
UPDATE update_once SET id = id, n = NEXTVAL('rhs_once') WHERE id = 1;
SELECT n, ts, CURRVAL('rhs_once') AS consumed FROM update_once;
CREATE SEQUENCE ts_once START WITH 1;
UPDATE legacy_ts SET ts = FROM_UNIXTIME(1700000000 + NEXTVAL('ts_once')) WHERE id = 1;
SELECT ts, CURRVAL('ts_once') AS consumed FROM legacy_ts WHERE id = 1;
CREATE TABLE typed_ts (ts TIMESTAMP(0));
INSERT INTO typed_ts VALUES ('1970-01-01 00:00:01'), ('2024-01-02 03:04:05');
SELECT ts, ADDTIME(ts, '00:00:00.000001'), SUBTIME(ts, '-00:00:00.000001'), DATE_SUB(ts, INTERVAL 2 SECOND) FROM typed_ts ORDER BY ts;
SET sql_mode = 'STRICT_TRANS_TABLES,TIME_TRUNCATE_FRACTIONAL';
SELECT CAST('2024.01.02 03:04:05.9999999' AS DATETIME(6));
CREATE TABLE duration (v TIME);
INSERT IGNORE INTO duration VALUES ('12:34:56.9999999junk');
SHOW WARNINGS;
SELECT v FROM duration;
SET sql_mode = 'STRICT_TRANS_TABLES';
SELECT CAST('2024.01.02 03:04:05.9999999' AS DATETIME(6));
CREATE SEQUENCE dml_once START WITH 1;
INSERT INTO legacy_ts VALUES (4, FROM_UNIXTIME(1700000000 + NEXTVAL('dml_once')));
SELECT ts, CURRVAL('dml_once') AS consumed FROM legacy_ts WHERE id = 4;
INSERT INTO legacy_ts VALUES (4, NULL) ON DUPLICATE KEY UPDATE ts = FROM_UNIXTIME(1700000000 + NEXTVAL('dml_once'));
SELECT ts, CURRVAL('dml_once') AS consumed FROM legacy_ts WHERE id = 4;
-- Joined assignments use the simultaneous row image and share their values
-- with automatic-column predicates, including DEFAULT and target selectors.
CREATE TABLE joined_update (id INT PRIMARY KEY, n INT DEFAULT 7, a INT, b INT, ts TIMESTAMP(6) NOT NULL DEFAULT '2000-01-01 00:00:00' ON UPDATE CURRENT_TIMESTAMP(6));
CREATE TABLE joined_source (id INT PRIMARY KEY, a INT);
INSERT INTO joined_update VALUES (1, 7, 1, 2, '2000-01-01 00:00:00'), (2, 7, 3, 4, '2000-01-01 00:00:00');
INSERT INTO joined_source VALUES (1, 0);
UPDATE joined_update t JOIN joined_source s ON t.id = s.id SET t.n = DEFAULT;
SELECT n, ts FROM joined_update ORDER BY id;
CREATE SEQUENCE joined_rhs START WITH 7;
UPDATE joined_update t JOIN joined_source s ON t.id = s.id SET t.n = NEXTVAL('joined_rhs');
SELECT n, ts, CURRVAL('joined_rhs') AS consumed FROM joined_update WHERE id = 1;
UPDATE joined_update t JOIN joined_source s ON t.id = s.id SET t.a = t.b, t.b = t.a;
SELECT a, b FROM joined_update WHERE id = 1;
CREATE SEQUENCE inactive_rhs START WITH 1;
UPDATE joined_update t LEFT JOIN joined_source s ON t.id = s.id SET t.a = t.a, s.a = NEXTVAL('inactive_rhs');
SELECT a, CURRVAL('inactive_rhs') AS consumed FROM joined_source;
INSERT INTO joined_source VALUES (2, 0);
CREATE SEQUENCE duplicate_rhs START WITH 7;
UPDATE joined_update t JOIN joined_source s ON t.id = 1 SET t.n = NEXTVAL('duplicate_rhs'), s.a = s.a;
SELECT n, CURRVAL('duplicate_rhs') AS consumed FROM joined_update WHERE id = 1;
-- Reuse the same prepared handles through session state A -> B -> A.
SET lc_time_names = 'en_US';
PREPARE locale_query FROM 'SELECT CONCAT(DAYNAME("2024-01-07"), "/", DATE_FORMAT("2024-12-01", "%M")) AS names';
EXECUTE locale_query;
SET lc_time_names = 'fr_FR';
EXECUTE locale_query;
SET lc_time_names = 'en_US';
EXECUTE locale_query;
DEALLOCATE PREPARE locale_query;
SET sql_mode = '';
PREPARE fractional_query FROM 'SELECT CAST("2024-01-02 03:04:05.9999999" AS DATETIME(6)), CAST("12:34:56.9999999" AS TIME(6))';
EXECUTE fractional_query;
SET sql_mode = 'TIME_TRUNCATE_FRACTIONAL';
EXECUTE fractional_query;
SELECT CAST(123456.987654 AS TIME(3)), CAST(-123456.987654 AS TIME(3)), CAST(20240102030405.9999999 AS DATETIME(6)), CAST(20240102030405.987654 AS TIMESTAMP(3));
CREATE TABLE legacy_definition (first_ts TIMESTAMP(6) DEFAULT '2000-01-01 00:00:00', later_ts TIMESTAMP(6), nullable_ts TIMESTAMP(6) NULL);
INSERT INTO legacy_definition VALUES (NULL, NULL, NULL);
SELECT first_ts, later_ts, nullable_ts FROM legacy_definition;
INSERT INTO legacy_definition () VALUES ();
SELECT CAST(first_ts AS VARCHAR), CAST(later_ts AS VARCHAR), nullable_ts FROM legacy_definition ORDER BY first_ts;
SET sql_mode = '';
EXECUTE fractional_query;
DEALLOCATE PREPARE fractional_query;
-- Test the registered MAKEDATE path, not a direct-only compatibility helper.
SELECT MAKEDATE(24.5, 32), MAKEDATE(69, 1), MAKEDATE(70, 1), MAKEDATE(2024, 0);
DROP DATABASE temporal_28932;
SET explicit_defaults_for_timestamp = @old_explicit_defaults;
SET sql_mode = @old_sql_mode;
SET time_zone = @old_time_zone;
SET lc_time_names = @old_lc_time_names;
SET timestamp = 0;
