{
 "title": "MO-Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "mysql" }
  ]
 },
 "panels": [
  { "title": "MO-Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Statement Total",
   "type": "timeseries",
   "description": "processed statement count increasing rate in the past 30 seconds",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(collecttime, \"30s\", 0) AS time_sec,\n  avg(value) as value,\n  type as metric\nFROM sql_statement_total\nWHERE\n  $__timeFilter(collecttime) AND internal=\"0\"\nGROUP BY $__timeGroup(collecttime, \"30s\", 0), type\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Statement Latency",
   "type": "timeseries",
   "description": "SQL processing time in seconds, averaged by the past 30 seconds",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(collecttime, \"30s\", 0) AS time_sec,\n  avg(value) as value,\n  type as metric\nFROM sql_latency_seconds\nWHERE\n  $__timeFilter(collecttime) AND internal=\"0\"\nGROUP BY $__timeGroup(collecttime, \"30s\", 0), type\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Process CPU Time",
   "type": "timeseries",
   "description": "Total CPU time in used by MO server",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(collecttime) as time_sec,\n  value as cpu\nFROM process_cpu_percent\nWHERE $__timeFilter(collecttime)\nORDER BY collecttime"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "description": "Total memory used by MO server，averaged by the past 1 minute",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(collecttime) as time_sec,\n  value as memory\nFROM process_resident_memory_bytes\nWHERE $__timeFilter(collecttime)\nORDER BY collecttime"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "description": "number of open file descriptors and its max limit",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n unix_timestamp(collecttime) as time_sec,\n  value as open\nFROM process_open_fds\nWHERE\n  $__timeFilter(collecttime)\nORDER BY collecttime"
    },
    {
     "rawSql": "SELECT\n unix_timestamp(collecttime) as time_sec,\n  value as `limitation`\nFROM process_max_fds\nWHERE\n  $__timeFilter(collecttime)\nORDER BY collecttime\n"
    }
   ]
  },
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Percentage",
   "type": "timeseries",
   "description": "CPU Percentage on the current machine, averaged by the number of logical cores",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(collecttime) as time_sec,\n  value as cpu\nFROM sys_cpu_combined_percent\nWHERE $__timeFilter(collecttime)\nORDER BY collecttime"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Memory usage on the current machine",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(collecttime) as time_sec,\n  value as used\nFROM sys_memory_used\nWHERE $__timeFilter(collecttime)\nORDER BY collecttime"
    },
    {
     "rawSql": "SELECT\n  unix_timestamp(collecttime) as time_sec,\n  value as available\nFROM sys_memory_available\nWHERE $__timeFilter(collecttime)\nORDER BY collecttime"
    }
   ]
  }
 ]
}