create publication pub1 database t;
create account acc0 admin_name 'root' identified by '111';
create account acc1 admin_name 'root' identified by '111';
create account acc2 admin_name 'root' identified by '111';
create database t;
create publication pub1 database t;
create publication pub2 database t account all;
create publication pub3 database t account acc0,acc1;
create publication pub4 database t account acc0,acc1,accx;
create publication pub5 database t account accx comment 'test';
show publications;
show create publication pub1;
show create publication pub2;
show create publication pub5;
alter publication pub1 account acc0,acc1;
show create publication pub1;
alter publication pub2 account drop acc1;
show create publication pub2;
alter publication pub3 account add accx;
show create publication pub3;
alter publication pub4 account drop acc1,acc2;
show create publication pub4;
alter publication pub5 account all comment '1212';
show create publication pub5;
drop publication pub1;
show publications;
create publication pub1 database t;
create publication pub1 database t;
alter publication pub1 account `all`;
show create publication pub1;
show create publication pubx;
drop publication pub1;
drop publication pub2;
drop publication pub3;
drop publication pub4;
drop publication pub5;
drop account acc0;
drop account acc1;
drop account acc2;
drop database t;