# Log level: debug, info, warn, error, fatal.
level = "info"

# Log format, one of json or text.
format = "console"

# File logging.
[file]
# Log file name.
filename = ""

# Max log file size in MB (upper limit to 4096MB).
max-size = 512

# Max log file keep days. No clean up by default.
max-days = 0

# Maximum number of old log files to retain. No clean up by default.
max-backups = 0
