// Copyright 2021 Matrix Origin
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package objectio

import (
	"context"
	"fmt"
	"strings"

	"github.com/matrixorigin/matrixone/pkg/common/moerr"
	"github.com/matrixorigin/matrixone/pkg/defines"
	"github.com/matrixorigin/matrixone/pkg/fileservice"
)

// Offline fs kinds, matching the --local / --s3 / --local2 tool flags. They
// select the on-disk format/layout of an offline data dir:
//   - local:  LocalFS, legacy CRC32-framed format
//   - local2: LocalFS, raw (checksum-free) DISK-V2 format
//   - s3:     S3FS over a local "disk" endpoint, raw (S3FS-on-disk) format
const (
	OfflineKindLocal  = "local"
	OfflineKindLocal2 = "local2"
	OfflineKindS3     = "s3"
)

// OfflineKind resolves the offline fs kind from the mutually-exclusive flags,
// falling back to deflt when none is set.
func OfflineKind(local, s3, local2 bool, deflt string) string {
	switch {
	case local2:
		return OfflineKindLocal2
	case s3:
		return OfflineKindS3
	case local:
		return OfflineKindLocal
	default:
		return deflt
	}
}

func TmpNewFileservice(ctx context.Context, dir string) fileservice.FileService {
	return tmpNewFileservice(ctx, defines.LocalFileServiceName, dir)
}

func TmpNewSharedFileservice(ctx context.Context, dir string) fileservice.FileService {
	return tmpNewFileservice(ctx, defines.SharedFileServiceName, dir)
}

func tmpNewFileservice(ctx context.Context, kind string, dir string) fileservice.FileService {
	c := fileservice.Config{
		Name:    kind,
		Backend: "DISK",
		DataDir: dir,
		Cache:   fileservice.DisabledCacheConfig,
	}
	service, err := fileservice.NewFileService(ctx, c, nil)
	if err != nil {
		err = moerr.NewInternalErrorNoCtx(fmt.Sprintf("NewFileService failed: %s", err.Error()))
		panic(any(err))
	}
	return service
}

// NewOfflineFS creates a file service for reading an offline data directory in
// the on-disk format selected by kind (see the OfflineKind* constants):
//   - s3:     data generated by the S3-backed fileservice (raw, S3FS-on-disk)
//   - local2: data generated by the DISK-V2 LocalFS (raw)
//   - local:  data generated by the legacy DISK LocalFS (CRC32-framed)
func NewOfflineFS(
	ctx context.Context,
	dir string,
	kind string,
) (fs fileservice.FileService, err error) {
	switch strings.ToLower(kind) {
	case OfflineKindS3:
		cfg := fileservice.ObjectStorageArguments{
			Name:     defines.SharedFileServiceName,
			Endpoint: "DISK",
			Bucket:   dir,
		}
		fs, err = fileservice.NewS3FS(ctx, cfg, fileservice.DisabledCacheConfig, nil, false, true)
		return

	case OfflineKindLocal2:
		cfg := fileservice.Config{
			Name:    defines.LocalFileServiceName,
			Backend: "DISK-V2",
			DataDir: dir,
			Cache:   fileservice.DisabledCacheConfig,
		}
		fs, err = fileservice.NewFileService(ctx, cfg, nil)
		return

	default: // OfflineKindLocal
		cfg := fileservice.Config{
			Name:    defines.LocalFileServiceName,
			Backend: "DISK",
			DataDir: dir,
			Cache:   fileservice.DisabledCacheConfig,
		}
		fs, err = fileservice.NewFileService(ctx, cfg, nil)
		return
	}
}
