service-type = "CN"

[log]
level = "debug"
format = "console"
max-size = 512

[cn.rpc]
max-message-size = "100mb"

[[fileservice]]
backend = "DISK"
data-dir = "/var/lib/matrixone/data"
name = "LOCAL"

[[fileservice]]
backend = "S3"
name = "S3"

[fileservice.s3]
bucket = "matrixorigin-docker-compose-test"
endpoint = "https://s3.us-west-2.amazonaws.com"
key-prefix = "server/data"

[[fileservice]]
backend = "S3"
name = "ETL"

[fileservice.s3]
bucket = "matrixorigin-docker-compose-test"
endpoint = "https://s3.us-west-2.amazonaws.com"
key-prefix = "server/etl"

[hakeeper-client]
service-addresses = ["logservice-0:32001"]

[observability]
disableTrace = true
disableMetric = true

[cn]
uuid = "dd1dccb8-4d3c-41f9-b482-5251dc7a41bf"
listen-address = "0.0.0.0:6002"
service-address = "cn-0:6002"
sql-address = "cn-0:6001"

[cn.Engine]
type = "distributed-tae"

[cn.frontend]
port = 6001