service-type = "CN"
data-dir = "./mo-data"

[log]
level = "info"
format = "console"
max-size = 512

[hakeeper-client]
service-addresses = [
  "127.0.0.1:32001",
]

[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "SHARED"
backend = "DISK"
data-dir = "mo-data/shared"

[fileservice.cache]
memory-capacity = "128MB"
disk-capacity = "1GB"
disk-path = "mo-data/file-service-cache"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"

[observability]
disableTrace = true
disableMetric = true

[cn]
uuid = ""
port-base = 0

[cn.Engine]
type = "distributed-tae"

[cn.frontend]
port = 0
unix-socket = ""
