service-type = "CN"
data-dir = "./mo-data"

[log]
level = "info"

[cn]
uuid = "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"
port-base = 18000

[[fileservice]]
name = "SHARED"
backend = "S3" # for hdfs, the backend is also S3
[fileservice.s3]
endpoint = "hdfs://[name-node-address]:[name-node-port]" # must begin with "hdfs://" and must not be empty
bucket = "/user/mo" # root path in HDFS, must be existed and read-writable
user = "mo" # hdfs user name, must not be empty
# the following are optional
kerberos-service-principle-name = "" # kerberos service principle name
kerberos-username = "" # kerberos username
kerberos-realm = "" # kerberos realm
kerberos-password = "" # kerberos password
kerberos-keytab-path = "" # kerberos keytab path

