logservices = [
    "./etc/launch-with-proxy/log.toml",
]

tnservices = [
    "./etc/launch-with-proxy/tn.toml"
]

cnservices = [
    "./etc/launch-with-proxy/cn1.toml",
    "./etc/launch-with-proxy/cn2.toml"
]

proxy-services = [
    "./etc/launch-with-proxy/proxy.toml"
]
