create function sql_sum (a int, b int) returns int language sql as '$1 + $2';
select sql_sum(1, 1) as ret;
drop function sql_sum(int, int);
create database db1;
use db1;
select name, db from mo_catalog.mo_user_defined_function where db = 'db1';
create function helloworld () returns int language sql as 'select id from tbl1 limit 1';
select name, db from mo_catalog.mo_user_defined_function where db = 'db1';
drop database db1;
select name, db from mo_catalog.mo_user_defined_function where db = 'db1';
create function db1.helloworld5 () returns int language sql as 'select id from tbl1 limit 1';
create database db1;
use db1;
create function db1.helloworld5 () returns int language sql as 'select id from tbl1 limit 1';
drop function db1.helloworld5();
drop function db2.helloworld5();
drop database db1;
