create function sql_sum (a int, b int) returns int language sql as '$1 + $2';
select sql_sum(1, 1) as ret;
drop function sql_sum(int, int);
drop database if exists udf_db1;
create database udf_db1;
use udf_db1;
select name, db from mo_catalog.mo_user_defined_function where db = 'udf_db1';
create function helloworld () returns int language sql as 'select id from tbl1 limit 1';
select name, db from mo_catalog.mo_user_defined_function where db = 'udf_db1';
drop database if exists udf_db1;
select name, db from mo_catalog.mo_user_defined_function where db = 'udf_db1';
create function udf_db1.helloworld5 () returns int language sql as 'select id from tbl1 limit 1';
create database udf_db1;
use udf_db1;
create function udf_db1.helloworld5 () returns int language sql as 'select id from tbl1 limit 1';
drop function udf_db1.helloworld5();
drop function db2.helloworld5();
create function sql_nl() returns varchar language sql as $$select '\n'$$;
select hex(body) as body_hex from mo_catalog.mo_user_defined_function where name = 'sql_nl' and db = 'udf_db1';

drop table if exists udf_sql_mode_t;
create table udf_sql_mode_t(v varchar(10));
insert into udf_sql_mode_t values ('ok');
set sql_mode = 'PIPES_AS_CONCAT';
create function sql_mode_pipe() returns varchar language sql as $$select 'a'||'b'$$;
set sql_mode = '';
select sql_mode_pipe();
set sql_mode = 'ANSI_QUOTES';
create function sql_mode_ansi() returns varchar language sql as $$select "v" from "udf_sql_mode_t" limit 1$$;
set sql_mode = '';
select sql_mode_ansi();
drop function sql_mode_pipe();
drop function sql_mode_ansi();
drop table udf_sql_mode_t;
set sql_mode = default;
