create function sql_sum (a int, b int) returns int language sql as '$1 + $2';
select sql_sum(1, 1) as ret;
drop function sql_sum(int, int);
create function drop_if_exists (p_id int) returns int language sql as '$1';
drop function if exists drop_if_exists(p_id int);
drop function if exists drop_if_exists(p_id int);
drop database if exists udf_db1;
create database udf_db1;
use udf_db1;
select name, db from mo_catalog.mo_user_defined_function where db = 'udf_db1';
create function helloworld () returns int language sql as 'select id from tbl1 limit 1';
select name, db from mo_catalog.mo_user_defined_function where db = 'udf_db1';
drop database if exists udf_db1;
select name, db from mo_catalog.mo_user_defined_function where db = 'udf_db1';
create function udf_db1.helloworld5 () returns int language sql as 'select id from tbl1 limit 1';
create database udf_db1;
use udf_db1;
create function udf_db1.helloworld5 () returns int language sql as 'select id from tbl1 limit 1';
drop function udf_db1.helloworld5();
drop function db2.helloworld5();
create function sql_nl() returns varchar language sql as $$select '\n'$$;
select hex(body) as body_hex from mo_catalog.mo_user_defined_function where name = 'sql_nl' and db = 'udf_db1';

drop table if exists udf_sql_mode_t;
create table udf_sql_mode_t(v varchar(10));
insert into udf_sql_mode_t values ('ok');
set sql_mode = 'PIPES_AS_CONCAT';
create function sql_mode_pipe() returns varchar language sql as $$select 'a'||'b'$$;
set sql_mode = '';
select sql_mode_pipe();
set sql_mode = 'ANSI_QUOTES';
create function sql_mode_ansi() returns varchar language sql as $$select "v" from "udf_sql_mode_t" limit 1$$;
set sql_mode = '';
select sql_mode_ansi();
drop function sql_mode_pipe();
drop function sql_mode_ansi();
drop table udf_sql_mode_t;
set sql_mode = default;

drop table if exists udf_lookup_base;
drop function if exists udf_lookup(int);
create table udf_lookup_base (id int primary key, v int);
insert into udf_lookup_base values (1, 5), (2, 15), (3, 25), (4, null);
create function udf_lookup(p_id int) returns int language sql as 'select v from udf_lookup_base where id = $1';
select udf_lookup(2) as lookup_2;
select id, udf_lookup(id) as lookup_v from udf_lookup_base order by id;
select id from udf_lookup_base where udf_lookup(id) >= 15 order by id;
drop function udf_lookup(int);
drop table udf_lookup_base;

drop table if exists udf_marker_collision_base;
drop function if exists udf_marker_collision(int);
create table udf_marker_collision_base (`__mo_sql_udf_1_arg_1` int);
insert into udf_marker_collision_base values (7);
create function udf_marker_collision(p_id int) returns int language sql as 'select __mo_sql_udf_1_arg_1 from udf_marker_collision_base where $1 = $1';
select udf_marker_collision(cast(5 as int)) as collision_safe;
drop function udf_marker_collision(int);
drop table udf_marker_collision_base;
