// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: partition.proto

package partition

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	plan "github.com/matrixorigin/matrixone/pkg/pb/plan"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PartitionMethod partition method
type PartitionMethod int32

const (
	PartitionMethod_Key        PartitionMethod = 0
	PartitionMethod_LinearKey  PartitionMethod = 1
	PartitionMethod_Hash       PartitionMethod = 2
	PartitionMethod_LinearHash PartitionMethod = 3
	PartitionMethod_Range      PartitionMethod = 4
	PartitionMethod_List       PartitionMethod = 5
)

var PartitionMethod_name = map[int32]string{
	0: "Key",
	1: "LinearKey",
	2: "Hash",
	3: "LinearHash",
	4: "Range",
	5: "List",
}

var PartitionMethod_value = map[string]int32{
	"Key":        0,
	"LinearKey":  1,
	"Hash":       2,
	"LinearHash": 3,
	"Range":      4,
	"List":       5,
}

func (x PartitionMethod) String() string {
	return proto.EnumName(PartitionMethod_name, int32(x))
}

func (PartitionMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12ead894473a209c, []int{0}
}

type PartitionMetadata struct {
	TableID              uint64          `protobuf:"varint,1,opt,name=TableID,proto3" json:"TableID,omitempty"`
	TableName            string          `protobuf:"bytes,2,opt,name=TableName,proto3" json:"TableName,omitempty"`
	DatabaseName         string          `protobuf:"bytes,3,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	Method               PartitionMethod `protobuf:"varint,4,opt,name=Method,proto3,enum=partition.PartitionMethod" json:"Method,omitempty"`
	Description          string          `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	Columns              []string        `protobuf:"bytes,6,rep,name=Columns,proto3" json:"Columns,omitempty"`
	Partitions           []Partition     `protobuf:"bytes,7,rep,name=Partitions,proto3" json:"Partitions"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PartitionMetadata) Reset()         { *m = PartitionMetadata{} }
func (m *PartitionMetadata) String() string { return proto.CompactTextString(m) }
func (*PartitionMetadata) ProtoMessage()    {}
func (*PartitionMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_12ead894473a209c, []int{0}
}
func (m *PartitionMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PartitionMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PartitionMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PartitionMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionMetadata.Merge(m, src)
}
func (m *PartitionMetadata) XXX_Size() int {
	return m.ProtoSize()
}
func (m *PartitionMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionMetadata proto.InternalMessageInfo

func (m *PartitionMetadata) GetTableID() uint64 {
	if m != nil {
		return m.TableID
	}
	return 0
}

func (m *PartitionMetadata) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *PartitionMetadata) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *PartitionMetadata) GetMethod() PartitionMethod {
	if m != nil {
		return m.Method
	}
	return PartitionMethod_Key
}

func (m *PartitionMetadata) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PartitionMetadata) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *PartitionMetadata) GetPartitions() []Partition {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type Partition struct {
	PartitionID          uint64     `protobuf:"varint,1,opt,name=PartitionID,proto3" json:"PartitionID,omitempty"`
	PartitionTableName   string     `protobuf:"bytes,2,opt,name=PartitionTableName,proto3" json:"PartitionTableName,omitempty"`
	PrimaryTableID       uint64     `protobuf:"varint,3,opt,name=PrimaryTableID,proto3" json:"PrimaryTableID,omitempty"`
	Name                 string     `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Position             uint32     `protobuf:"varint,5,opt,name=Position,proto3" json:"Position,omitempty"`
	ExprStr              string     `protobuf:"bytes,6,opt,name=ExprStr,proto3" json:"ExprStr,omitempty"`
	Expr                 *plan.Expr `protobuf:"bytes,7,opt,name=Expr,proto3" json:"Expr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Partition) Reset()         { *m = Partition{} }
func (m *Partition) String() string { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()    {}
func (*Partition) Descriptor() ([]byte, []int) {
	return fileDescriptor_12ead894473a209c, []int{1}
}
func (m *Partition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Partition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Partition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Partition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partition.Merge(m, src)
}
func (m *Partition) XXX_Size() int {
	return m.ProtoSize()
}
func (m *Partition) XXX_DiscardUnknown() {
	xxx_messageInfo_Partition.DiscardUnknown(m)
}

var xxx_messageInfo_Partition proto.InternalMessageInfo

func (m *Partition) GetPartitionID() uint64 {
	if m != nil {
		return m.PartitionID
	}
	return 0
}

func (m *Partition) GetPartitionTableName() string {
	if m != nil {
		return m.PartitionTableName
	}
	return ""
}

func (m *Partition) GetPrimaryTableID() uint64 {
	if m != nil {
		return m.PrimaryTableID
	}
	return 0
}

func (m *Partition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Partition) GetPosition() uint32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *Partition) GetExprStr() string {
	if m != nil {
		return m.ExprStr
	}
	return ""
}

func (m *Partition) GetExpr() *plan.Expr {
	if m != nil {
		return m.Expr
	}
	return nil
}

func init() {
	proto.RegisterEnum("partition.PartitionMethod", PartitionMethod_name, PartitionMethod_value)
	proto.RegisterType((*PartitionMetadata)(nil), "partition.PartitionMetadata")
	proto.RegisterType((*Partition)(nil), "partition.Partition")
}

func init() { proto.RegisterFile("partition.proto", fileDescriptor_12ead894473a209c) }

var fileDescriptor_12ead894473a209c = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xb3, 0xb1, 0x93, 0xd4, 0x13, 0x9a, 0x86, 0x11, 0x87, 0x55, 0x84, 0x8c, 0x95, 0x03,
	0xb2, 0x90, 0xb0, 0x25, 0x73, 0xe3, 0x58, 0x82, 0x54, 0x44, 0x8b, 0x22, 0xc3, 0x01, 0x71, 0x5b,
	0x37, 0x8b, 0xb3, 0x22, 0xf6, 0x5a, 0xeb, 0x8d, 0xd4, 0x3e, 0x0b, 0x17, 0x1e, 0xa7, 0xc7, 0x3e,
	0x01, 0x82, 0xf0, 0x00, 0xbc, 0x02, 0xf2, 0xa6, 0xde, 0x9a, 0xa8, 0xb7, 0xf9, 0xfe, 0xf9, 0xf3,
	0x67, 0x3c, 0x3b, 0x70, 0x52, 0x31, 0xa5, 0x85, 0x16, 0xb2, 0x8c, 0x2a, 0x25, 0xb5, 0x44, 0xcf,
	0x0a, 0x33, 0xa8, 0x36, 0xec, 0x4e, 0x9e, 0xbd, 0xcc, 0x85, 0x5e, 0x6f, 0xb3, 0xe8, 0x52, 0x16,
	0x71, 0x2e, 0x73, 0x19, 0x1b, 0x39, 0xdb, 0x7e, 0x35, 0x64, 0xc0, 0x54, 0x7b, 0xfb, 0xfc, 0x7b,
	0x1f, 0x1e, 0x2f, 0xdb, 0xa0, 0x0b, 0xae, 0xd9, 0x8a, 0x69, 0x86, 0x14, 0x46, 0x9f, 0x58, 0xb6,
	0xe1, 0xef, 0x16, 0x94, 0x04, 0x24, 0x74, 0xd3, 0x16, 0xf1, 0x29, 0x78, 0xa6, 0xfc, 0xc0, 0x0a,
	0x4e, 0xfb, 0x01, 0x09, 0xbd, 0xf4, 0x5e, 0xc0, 0x39, 0x3c, 0x5a, 0x30, 0xcd, 0x32, 0x56, 0xef,
	0x0d, 0x8e, 0x31, 0xfc, 0xa7, 0x61, 0x02, 0xc3, 0x0b, 0xae, 0xd7, 0x72, 0x45, 0xdd, 0x80, 0x84,
	0x93, 0x64, 0x16, 0xdd, 0x7f, 0x59, 0x77, 0x92, 0xb5, 0x5c, 0xa5, 0x77, 0x4e, 0x0c, 0x60, 0xbc,
	0xe0, 0xf5, 0xa5, 0x12, 0x55, 0xd3, 0xa4, 0x03, 0x13, 0xdb, 0x95, 0x9a, 0x89, 0xdf, 0xc8, 0xcd,
	0xb6, 0x28, 0x6b, 0x3a, 0x0c, 0x9c, 0xd0, 0x4b, 0x5b, 0xc4, 0xd7, 0x00, 0x36, 0xb6, 0xa6, 0xa3,
	0xc0, 0x09, 0xc7, 0xc9, 0x93, 0x87, 0xfe, 0xf3, 0xd4, 0xbd, 0xf9, 0xf9, 0xac, 0x97, 0x76, 0xdc,
	0xf3, 0xbf, 0x04, 0x3c, 0x8b, 0xcd, 0x14, 0x16, 0xec, 0x66, 0xba, 0x12, 0x46, 0x80, 0x16, 0x0f,
	0xd7, 0xf4, 0x40, 0x07, 0x9f, 0xc3, 0x64, 0xa9, 0x44, 0xc1, 0xd4, 0x75, 0xbb, 0x6e, 0xc7, 0x84,
	0x1e, 0xa8, 0x88, 0xe0, 0x9a, 0x24, 0xd7, 0x24, 0x99, 0x1a, 0x67, 0x70, 0xb4, 0x94, 0xb5, 0xb0,
	0x0b, 0x39, 0x4e, 0x2d, 0x37, 0xdb, 0x78, 0x7b, 0x55, 0xa9, 0x8f, 0x5a, 0xd1, 0xa1, 0xf9, 0x49,
	0x8b, 0xe8, 0x83, 0xdb, 0x94, 0x74, 0x14, 0x90, 0x70, 0x9c, 0x40, 0x64, 0x2e, 0xa7, 0x51, 0x52,
	0xa3, 0xbf, 0xf8, 0x0c, 0x27, 0x07, 0x8f, 0x80, 0x23, 0x70, 0xde, 0xf3, 0xeb, 0x69, 0x0f, 0x8f,
	0xc1, 0x3b, 0x17, 0x25, 0x67, 0xaa, 0x41, 0x82, 0x47, 0xe0, 0x9e, 0xb1, 0x7a, 0x3d, 0xed, 0xe3,
	0x04, 0x60, 0xdf, 0x30, 0xec, 0xa0, 0x07, 0x83, 0x94, 0x95, 0x39, 0x9f, 0xba, 0x8d, 0xe9, 0x5c,
	0xd4, 0x7a, 0x3a, 0x38, 0x3d, 0xbb, 0xfd, 0xed, 0x93, 0x9b, 0x9d, 0x4f, 0x6e, 0x77, 0x3e, 0xf9,
	0xb5, 0xf3, 0x7b, 0x3f, 0xfe, 0xf8, 0xe4, 0x4b, 0xd2, 0x39, 0xd7, 0x82, 0x69, 0x25, 0xae, 0xa4,
	0x12, 0xb9, 0x28, 0x5b, 0x28, 0x79, 0x5c, 0x7d, 0xcb, 0xe3, 0x2a, 0x8b, 0xed, 0x8b, 0x65, 0x43,
	0x73, 0xba, 0xaf, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xba, 0xca, 0xb3, 0xd4, 0x13, 0x03, 0x00,
	0x00,
}

func (m *PartitionMetadata) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PartitionMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PartitionMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Partitions) > 0 {
		for iNdEx := len(m.Partitions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Partitions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPartition(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Columns) > 0 {
		for iNdEx := len(m.Columns) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Columns[iNdEx])
			copy(dAtA[i:], m.Columns[iNdEx])
			i = encodeVarintPartition(dAtA, i, uint64(len(m.Columns[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintPartition(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Method != 0 {
		i = encodeVarintPartition(dAtA, i, uint64(m.Method))
		i--
		dAtA[i] = 0x20
	}
	if len(m.DatabaseName) > 0 {
		i -= len(m.DatabaseName)
		copy(dAtA[i:], m.DatabaseName)
		i = encodeVarintPartition(dAtA, i, uint64(len(m.DatabaseName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TableName) > 0 {
		i -= len(m.TableName)
		copy(dAtA[i:], m.TableName)
		i = encodeVarintPartition(dAtA, i, uint64(len(m.TableName)))
		i--
		dAtA[i] = 0x12
	}
	if m.TableID != 0 {
		i = encodeVarintPartition(dAtA, i, uint64(m.TableID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Partition) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Partition) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Partition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Expr != nil {
		{
			size, err := m.Expr.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPartition(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ExprStr) > 0 {
		i -= len(m.ExprStr)
		copy(dAtA[i:], m.ExprStr)
		i = encodeVarintPartition(dAtA, i, uint64(len(m.ExprStr)))
		i--
		dAtA[i] = 0x32
	}
	if m.Position != 0 {
		i = encodeVarintPartition(dAtA, i, uint64(m.Position))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintPartition(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x22
	}
	if m.PrimaryTableID != 0 {
		i = encodeVarintPartition(dAtA, i, uint64(m.PrimaryTableID))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PartitionTableName) > 0 {
		i -= len(m.PartitionTableName)
		copy(dAtA[i:], m.PartitionTableName)
		i = encodeVarintPartition(dAtA, i, uint64(len(m.PartitionTableName)))
		i--
		dAtA[i] = 0x12
	}
	if m.PartitionID != 0 {
		i = encodeVarintPartition(dAtA, i, uint64(m.PartitionID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPartition(dAtA []byte, offset int, v uint64) int {
	offset -= sovPartition(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PartitionMetadata) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TableID != 0 {
		n += 1 + sovPartition(uint64(m.TableID))
	}
	l = len(m.TableName)
	if l > 0 {
		n += 1 + l + sovPartition(uint64(l))
	}
	l = len(m.DatabaseName)
	if l > 0 {
		n += 1 + l + sovPartition(uint64(l))
	}
	if m.Method != 0 {
		n += 1 + sovPartition(uint64(m.Method))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovPartition(uint64(l))
	}
	if len(m.Columns) > 0 {
		for _, s := range m.Columns {
			l = len(s)
			n += 1 + l + sovPartition(uint64(l))
		}
	}
	if len(m.Partitions) > 0 {
		for _, e := range m.Partitions {
			l = e.ProtoSize()
			n += 1 + l + sovPartition(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Partition) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PartitionID != 0 {
		n += 1 + sovPartition(uint64(m.PartitionID))
	}
	l = len(m.PartitionTableName)
	if l > 0 {
		n += 1 + l + sovPartition(uint64(l))
	}
	if m.PrimaryTableID != 0 {
		n += 1 + sovPartition(uint64(m.PrimaryTableID))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPartition(uint64(l))
	}
	if m.Position != 0 {
		n += 1 + sovPartition(uint64(m.Position))
	}
	l = len(m.ExprStr)
	if l > 0 {
		n += 1 + l + sovPartition(uint64(l))
	}
	if m.Expr != nil {
		l = m.Expr.ProtoSize()
		n += 1 + l + sovPartition(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovPartition(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPartition(x uint64) (n int) {
	return sovPartition(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PartitionMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPartition
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PartitionMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PartitionMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableID", wireType)
			}
			m.TableID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TableID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPartition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPartition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TableName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatabaseName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPartition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPartition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DatabaseName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			m.Method = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Method |= PartitionMethod(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPartition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPartition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Columns", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPartition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPartition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Columns = append(m.Columns, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Partitions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPartition
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPartition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Partitions = append(m.Partitions, Partition{})
			if err := m.Partitions[len(m.Partitions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPartition(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPartition
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Partition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPartition
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Partition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Partition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PartitionID", wireType)
			}
			m.PartitionID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PartitionID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PartitionTableName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPartition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPartition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PartitionTableName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrimaryTableID", wireType)
			}
			m.PrimaryTableID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrimaryTableID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPartition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPartition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Position", wireType)
			}
			m.Position = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Position |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExprStr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPartition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPartition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExprStr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expr", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPartition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPartition
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPartition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Expr == nil {
				m.Expr = &plan.Expr{}
			}
			if err := m.Expr.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPartition(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPartition
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPartition(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPartition
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPartition
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPartition
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPartition
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPartition
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPartition
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPartition        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPartition          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPartition = fmt.Errorf("proto: unexpected end of group")
)
