// Code generated by command: go run avx2.go -out avx2.s -stubs avx2_stubs.go. DO NOT EDIT.

package min

func int8MinAvx2Asm(x []int8, r []int8)

func int16MinAvx2Asm(x []int16, r []int16)

func int32MinAvx2Asm(x []int32, r []int32)

func uint8MinAvx2Asm(x []uint8, r []uint8)

func uint16MinAvx2Asm(x []uint16, r []uint16)

func uint32MinAvx2Asm(x []uint32, r []uint32)

func float32MinAvx2Asm(x []float32, r []float32)

func float64MinAvx2Asm(x []float64, r []float64)
