FROM matrixorigin/tester:go1.20-jdk8

WORKDIR /

RUN git clone https://github.com/matrixorigin/mo-tester.git && apt update && apt install -y mariadb-client

COPY . /matrixone

RUN cd mo-tester && sed -i 's/127.0.0.1/cn0/g' mo.yml

ENV LC_ALL 'C.UTF-8'

CMD ["/matrixone/optools/compose_bvt/entrypoint.sh"]