// Copyright 2021 Matrix Origin
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// le.go is generated by le.template and overloadGenerate.go, do not edit it directly.

package operator

import (
	"github.com/matrixorigin/matrixone/pkg/container/nulls"
	"github.com/matrixorigin/matrixone/pkg/container/types"
	"github.com/matrixorigin/matrixone/pkg/container/vector"
	"github.com/matrixorigin/matrixone/pkg/encoding"
	"github.com/matrixorigin/matrixone/pkg/vectorize/ge"
	"github.com/matrixorigin/matrixone/pkg/vectorize/le"
	"github.com/matrixorigin/matrixone/pkg/vm/process2"
	"unsafe"

	roaring "github.com/RoaringBitmap/roaring/roaring64"
)

// less equal operator's evaluation for arguments: [int8]
func FdsOpLessEqualInt8(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.([]int8), rv.Col.([]int8)
	rtl := 8
	switch {
	case lc && !rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.Int8LeNullableScalar(lvs[0], rvs, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.Int8LeScalar(lvs[0], rvs, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.Int8GeNullableScalar(rvs[0], lvs, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.Int8GeScalar(rvs[0], lvs, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs)]
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int8LeNullable(lvs, rvs, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int8LeNullable(lvs, rvs, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int8LeNullable(lvs, rvs, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.Int8Le(lvs, rvs, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}

// less equal operator's evaluation for arguments: [int16]
func FdsOpLessEqualInt16(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.([]int16), rv.Col.([]int16)
	rtl := 8
	switch {
	case lc && !rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.Int16LeNullableScalar(lvs[0], rvs, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.Int16LeScalar(lvs[0], rvs, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.Int16GeNullableScalar(rvs[0], lvs, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.Int16GeScalar(rvs[0], lvs, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs)]
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int16LeNullable(lvs, rvs, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int16LeNullable(lvs, rvs, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int16LeNullable(lvs, rvs, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.Int16Le(lvs, rvs, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}

// less equal operator's evaluation for arguments: [int32]
func FdsOpLessEqualInt32(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.([]int32), rv.Col.([]int32)
	rtl := 8
	switch {
	case lc && !rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.Int32LeNullableScalar(lvs[0], rvs, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.Int32LeScalar(lvs[0], rvs, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.Int32GeNullableScalar(rvs[0], lvs, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.Int32GeScalar(rvs[0], lvs, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs)]
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int32LeNullable(lvs, rvs, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int32LeNullable(lvs, rvs, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int32LeNullable(lvs, rvs, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.Int32Le(lvs, rvs, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}

// less equal operator's evaluation for arguments: [int64]
func FdsOpLessEqualInt64(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.([]int64), rv.Col.([]int64)
	rtl := 8
	switch {
	case lc && !rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.Int64LeNullableScalar(lvs[0], rvs, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.Int64LeScalar(lvs[0], rvs, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.Int64GeNullableScalar(rvs[0], lvs, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.Int64GeScalar(rvs[0], lvs, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs)]
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int64LeNullable(lvs, rvs, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int64LeNullable(lvs, rvs, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int64LeNullable(lvs, rvs, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.Int64Le(lvs, rvs, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}

// less equal operator's evaluation for arguments: [uint8]
func FdsOpLessEqualUint8(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.([]uint8), rv.Col.([]uint8)
	rtl := 8
	switch {
	case lc && !rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.Uint8LeNullableScalar(lvs[0], rvs, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.Uint8LeScalar(lvs[0], rvs, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.Uint8GeNullableScalar(rvs[0], lvs, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.Uint8GeScalar(rvs[0], lvs, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs)]
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Uint8LeNullable(lvs, rvs, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Uint8LeNullable(lvs, rvs, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Uint8LeNullable(lvs, rvs, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.Uint8Le(lvs, rvs, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}

// less equal operator's evaluation for arguments: [uint16]
func FdsOpLessEqualUint16(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.([]uint16), rv.Col.([]uint16)
	rtl := 8
	switch {
	case lc && !rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.Uint16LeNullableScalar(lvs[0], rvs, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.Uint16LeScalar(lvs[0], rvs, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.Uint16GeNullableScalar(rvs[0], lvs, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.Uint16GeScalar(rvs[0], lvs, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs)]
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Uint16LeNullable(lvs, rvs, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Uint16LeNullable(lvs, rvs, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Uint16LeNullable(lvs, rvs, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.Uint16Le(lvs, rvs, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}

// less equal operator's evaluation for arguments: [uint32]
func FdsOpLessEqualUint32(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.([]uint32), rv.Col.([]uint32)
	rtl := 8
	switch {
	case lc && !rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.Uint32LeNullableScalar(lvs[0], rvs, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.Uint32LeScalar(lvs[0], rvs, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.Uint32GeNullableScalar(rvs[0], lvs, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.Uint32GeScalar(rvs[0], lvs, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs)]
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Uint32LeNullable(lvs, rvs, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Uint32LeNullable(lvs, rvs, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Uint32LeNullable(lvs, rvs, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.Uint32Le(lvs, rvs, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}

// less equal operator's evaluation for arguments: [uint64]
func FdsOpLessEqualUint64(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.([]uint64), rv.Col.([]uint64)
	rtl := 8
	switch {
	case lc && !rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.Uint64LeNullableScalar(lvs[0], rvs, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.Uint64LeScalar(lvs[0], rvs, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.Uint64GeNullableScalar(rvs[0], lvs, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.Uint64GeScalar(rvs[0], lvs, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs)]
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Uint64LeNullable(lvs, rvs, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Uint64LeNullable(lvs, rvs, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Uint64LeNullable(lvs, rvs, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.Uint64Le(lvs, rvs, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}

// less equal operator's evaluation for arguments: [float32]
func FdsOpLessEqualFloat32(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.([]float32), rv.Col.([]float32)
	rtl := 8
	switch {
	case lc && !rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.Float32LeNullableScalar(lvs[0], rvs, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.Float32LeScalar(lvs[0], rvs, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.Float32GeNullableScalar(rvs[0], lvs, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.Float32GeScalar(rvs[0], lvs, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs)]
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Float32LeNullable(lvs, rvs, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Float32LeNullable(lvs, rvs, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Float32LeNullable(lvs, rvs, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.Float32Le(lvs, rvs, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}

// less equal operator's evaluation for arguments: [float64]
func FdsOpLessEqualFloat64(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.([]float64), rv.Col.([]float64)
	rtl := 8
	switch {
	case lc && !rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.Float64LeNullableScalar(lvs[0], rvs, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.Float64LeScalar(lvs[0], rvs, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.Float64GeNullableScalar(rvs[0], lvs, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.Float64GeScalar(rvs[0], lvs, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs)]
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Float64LeNullable(lvs, rvs, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Float64LeNullable(lvs, rvs, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Float64LeNullable(lvs, rvs, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.Float64Le(lvs, rvs, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}

// less equal operator's evaluation for arguments: [char]
func FdsOpLessEqualChar(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.(*types.Bytes), rv.Col.(*types.Bytes)
	rtl := 8
	switch {
	case lc && !rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs.Lengths)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs.Lengths)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.StrLeNullableScalar(lvs.Data, rvs, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.StrLeScalar(lvs.Data, rvs, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs.Lengths)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs.Lengths)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.StrGeNullableScalar(rvs.Data, lvs, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.StrGeScalar(rvs.Data, lvs, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs.Lengths)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs.Lengths)]
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.StrLeNullable(lvs, rvs, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.StrLeNullable(lvs, rvs, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.StrLeNullable(lvs, rvs, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.StrLe(lvs, rvs, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}

// less equal operator's evaluation for arguments: [varchar]
func FdsOpLessEqualVarchar(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.(*types.Bytes), rv.Col.(*types.Bytes)
	rtl := 8
	switch {
	case lc && !rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs.Lengths)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs.Lengths)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.StrLeNullableScalar(lvs.Data, rvs, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.StrLeScalar(lvs.Data, rvs, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs.Lengths)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs.Lengths)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.StrGeNullableScalar(rvs.Data, lvs, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.StrGeScalar(rvs.Data, lvs, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs.Lengths)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs.Lengths)]
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.StrLeNullable(lvs, rvs, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.StrLeNullable(lvs, rvs, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.StrLeNullable(lvs, rvs, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.StrLe(lvs, rvs, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}

// less equal operator's evaluation for arguments: [date]
func FdsOpLessEqualDate(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.([]types.Date), rv.Col.([]types.Date)
	rtl := 8
	switch {
	case lc && !rc:
		rvsInInt32 := *(*[]int32)(unsafe.Pointer(&rvs))
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.Int32LeNullableScalar(int32(lvs[0]), rvsInInt32, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.Int32LeScalar(int32(lvs[0]), rvsInInt32, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		lvsInInt32 := *(*[]int32)(unsafe.Pointer(&lvs))
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.Int32GeNullableScalar(int32(rvs[0]), lvsInInt32, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.Int32GeScalar(int32(rvs[0]), lvsInInt32, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs)]
	rvsInInt32 := *(*[]int32)(unsafe.Pointer(&rvs))
	lvsInInt32 := *(*[]int32)(unsafe.Pointer(&lvs))
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int32LeNullable(lvsInInt32, rvsInInt32, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int32LeNullable(lvsInInt32, rvsInInt32, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int32LeNullable(lvsInInt32, rvsInInt32, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.Int32Le(lvsInInt32, rvsInInt32, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}

// less equal operator's evaluation for arguments: [datetime]
func FdsOpLessEqualDatetime(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.([]types.Datetime), rv.Col.([]types.Datetime)
	rtl := 8
	switch {
	case lc && !rc:
		rvsInInt64 := *(*[]int64)(unsafe.Pointer(&rvs))
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.Int64LeNullableScalar(int64(lvs[0]), rvsInInt64, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.Int64LeScalar(int64(lvs[0]), rvsInInt64, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		lvsInInt64 := *(*[]int64)(unsafe.Pointer(&lvs))
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.Int64GeNullableScalar(int64(rvs[0]), lvsInInt64, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.Int64GeScalar(int64(rvs[0]), lvsInInt64, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs)]
	rvsInInt64 := *(*[]int64)(unsafe.Pointer(&rvs))
	lvsInInt64 := *(*[]int64)(unsafe.Pointer(&lvs))
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int64LeNullable(lvsInInt64, rvsInInt64, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int64LeNullable(lvsInInt64, rvsInInt64, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int64LeNullable(lvsInInt64, rvsInInt64, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.Int64Le(lvsInInt64, rvsInInt64, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}

// less equal operator's evaluation for arguments: [timestamp]
func FdsOpLessEqualTimestamp(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.([]types.Timestamp), rv.Col.([]types.Timestamp)
	rtl := 8
	switch {
	case lc && !rc:
		rvsInInt64 := *(*[]int64)(unsafe.Pointer(&rvs))
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.Int64LeNullableScalar(int64(lvs[0]), rvsInInt64, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.Int64LeScalar(int64(lvs[0]), rvsInInt64, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		lvsInInt64 := *(*[]int64)(unsafe.Pointer(&lvs))
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.Int64GeNullableScalar(int64(rvs[0]), lvsInInt64, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.Int64GeScalar(int64(rvs[0]), lvsInInt64, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs)]
	rvsInInt64 := *(*[]int64)(unsafe.Pointer(&rvs))
	lvsInInt64 := *(*[]int64)(unsafe.Pointer(&lvs))
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int64LeNullable(lvsInInt64, rvsInInt64, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int64LeNullable(lvsInInt64, rvsInInt64, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Int64LeNullable(lvsInInt64, rvsInInt64, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.Int64Le(lvsInInt64, rvsInInt64, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}

// less equal operator's evaluation for arguments: [decimal64]
func FdsOpLessEqualDecimal64(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.([]types.Decimal64), rv.Col.([]types.Decimal64)
	rtl := 8
	switch {
	case lc && !rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.Decimal64LeNullableScalar(lvs[0], rvs, lv.Typ.Scale, rv.Typ.Scale, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.Decimal64LeScalar(lvs[0], rvs, lv.Typ.Scale, rv.Typ.Scale, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.Decimal64GeNullableScalar(rvs[0], lvs, rv.Typ.Scale, lv.Typ.Scale, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.Decimal64GeScalar(rvs[0], lvs, rv.Typ.Scale, lv.Typ.Scale, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs)]
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Decimal64LeNullable(lvs, rvs, lv.Typ.Scale, rv.Typ.Scale, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Decimal64LeNullable(lvs, rvs, lv.Typ.Scale, rv.Typ.Scale, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Decimal64LeNullable(lvs, rvs, lv.Typ.Scale, rv.Typ.Scale, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.Decimal64Le(lvs, rvs, lv.Typ.Scale, rv.Typ.Scale, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}

// less equal operator's evaluation for arguments: [decimal128]
func FdsOpLessEqualDecimal128(vs []*vector.Vector, proc *process.Process) (*vector.Vector, error) {
	lv := vs[0]
	rv := vs[1]
	lc := lv.IsConstant()
	rc := rv.IsConstant()
	lvs, rvs := lv.Col.([]types.Decimal128), rv.Col.([]types.Decimal128)
	rtl := 8
	switch {
	case lc && !rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(rvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(rvs)]
		if nulls.Any(rv.Nsp) {
			vector.SetCol(vec, le.Decimal128LeNullableScalar(lvs[0], rvs, lv.Typ.Scale, rv.Typ.Scale, rv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, le.Decimal128LeScalar(lvs[0], rvs, lv.Typ.Scale, rv.Typ.Scale, rs))
		}
		if rv.Ref == 0 {
			process.Put(proc, rv)
		}
		return vec, nil
	case !lc && rc:
		vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
		if err != nil {
			return nil, err
		}
		rs := encoding.DecodeInt64Slice(vec.Data)
		rs = rs[:len(lvs)]
		if nulls.Any(lv.Nsp) {
			vector.SetCol(vec, ge.Decimal128GeNullableScalar(rvs[0], lvs, rv.Typ.Scale, lv.Typ.Scale, lv.Nsp.Np, rs))
		} else {
			vector.SetCol(vec, ge.Decimal128GeScalar(rvs[0], lvs, rv.Typ.Scale, lv.Typ.Scale, rs))
		}
		if lv.Ref == 0 {
			process.Put(proc, lv)
		}
		return vec, nil
	}
	vec, err := process.Get(proc, int64(rtl)*int64(len(lvs)), SelsType)
	if err != nil {
		return nil, err
	}
	rs := encoding.DecodeInt64Slice(vec.Data)
	rs = rs[:len(lvs)]
	switch {
	case nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Decimal128LeNullable(lvs, rvs, lv.Typ.Scale, rv.Typ.Scale, roaring.Or(lv.Nsp.Np, rv.Nsp.Np), rs))
	case !nulls.Any(lv.Nsp) && nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Decimal128LeNullable(lvs, rvs, lv.Typ.Scale, rv.Typ.Scale, rv.Nsp.Np, rs))
	case nulls.Any(lv.Nsp) && !nulls.Any(rv.Nsp):
		vector.SetCol(vec, le.Decimal128LeNullable(lvs, rvs, lv.Typ.Scale, rv.Typ.Scale, lv.Nsp.Np, rs))
	default:
		vector.SetCol(vec, le.Decimal128Le(lvs, rvs, lv.Typ.Scale, rv.Typ.Scale, rs))
	}
	if lv.Ref == 0 {
		process.Put(proc, lv)
	}
	if rv.Ref == 0 {
		process.Put(proc, rv)
	}
	return vec, nil
}
