name: setup_env
description: "setup build environment"
inputs:
  go-version:
    description: 'version of golang'
    required: false
    default: "1.19"

runs:
  using: "composite"

  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
