name: setup_env
description: "setup build environment"
inputs:
  go-version:
    description: 'version of golang'
    required: false
    default: "1.21.5"
  cache:
    description: 'wether use cache'
    required: false
    default: "false"

runs:
  using: "composite"

  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }} 
        cache: ${{ inputs.cache }} 