# Define workflow name.
name: MatrixOne-v0.1.0

# Controls when the workflow will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch.
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: 0.1.0

  # Allows dev to run this workflow manually from the Actions tab
  workflow_dispatch:

    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build".
  build:
    # The type of runner that the job will run on.
    runs-on: self-hosted-0.1.0
    name: Build on CentOS/x64
    
    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it.
      - uses: actions/checkout@v2
        with:
          fetch-depth: '3'

      - name: Build Configure
        run: |
          cd $GITHUB_WORKSPACE && make clean && make config

      - name: Static Code Analysis
        run: |
          make sca 

      - name: Unit Testing
        run: |
          if [[ 'schedule' == ${{ github.event_name }} ]]; then
            make ut 
          else
            make ut SKIP_TEST="race"
          fi

      - name: Build Binary
        run: |
          make build

      - name: Build Verification Testing
        run: |
          make bvt 

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test_reports
          path: |
            ${{ github.workspace }}/coverage.html
          retention-days: 7 
