name: Command to Rerun Workflows
on:
  issue_comment:
    types: [created]
    
jobs:
  Rerun-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: guguducken/workflow-rerun-action@v0.0.3
        with:
          action-token: ${{ secrets.TOKEN_ACTION }}
          user: matrix-meow
          workflow-this: Command to Rerun Workflows