name: liucan_e2e_bvt(Standalone)

on:
  push:
    branches: [ "liucan_branch_dev" ]

jobs:
  bvt-linux-x86:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    name: e2e BVT Test on Linux/x64(LAUNCH)
    timeout-minutes: 60
    steps:
      - name: checkout head
        uses: actions/checkout@v3
        with:
          fetch-depth: '3'
          path: ./head
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Go
        uses: ./head/.github/actions/setup_env
      - name: Build MatrixOne
        run: |
          cd $GITHUB_WORKSPACE/head && make clean && make build
          git rev-parse --short HEAD
      - name: echo config
        run: |
          cd $GITHUB_WORKSPACE/head
          echo ""  >> ./etc/launch/cn.toml
          echo '[cn.txn]' >> ./etc/launch/cn.toml
          echo 'mode = "Optimistic"' >> ./etc/launch/cn.toml
          echo ""  >> ./etc/launch/tn.toml
          echo '[tn.txn]' >> ./etc/launch/tn.toml
          echo 'mode = "Optimistic"' >> ./etc/launch/tn.toml
          cat ./etc/launch/cn.toml
          cat ./etc/launch/tn.toml
      - name: Start MO
        run: |
          cd $GITHUB_WORKSPACE/head
          ./optools/run_bvt.sh $GITHUB_WORKSPACE/head launch
      - name: Clone test-tool repository
        uses: actions/checkout@v3
        with:
          repository: matrixorigin/mo-tester
          path: ./mo-tester
          ref: main
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
      - name: Start BVT Test
        id: bvt_on_pr_version
        run: |
          export LC_ALL="C.UTF-8"
          locale
          cd $GITHUB_WORKSPACE/mo-tester
          sed -i 's/  port: [0-9]*/  port: 12345/g' mo.yml
          cat mo.yml
          echo "============================="

          ./run.sh -n -g -o -p $GITHUB_WORKSPACE/head/test/distributed/cases -e pessimistic_transaction 2>&1
