name: MatrixOne Test

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

  workflow_dispatch:

jobs:
  bvt-docker-compose:
    runs-on: ubuntu-latest
    name: multi cn e2e bvt test docker compose
    timeout-minutes: 60

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker compose launch-tae-multi-CN-tae-DN
        run: |
          docker-compose -f etc/launch-tae-compose/compose.yaml --profile launch-tae-multi-CN-tae-DN up -d --build

      - name: Clone test-tool repository
        uses: actions/checkout@v2
        with:
          repository: matrixorigin/mo-tester
          path: ./mo-tester
          ref: main

      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64

      - name: Start BVT Test
        id: bvt_on_pr_version
        run: |
          export LC_ALL="C.UTF-8"
          locale
          cd $GITHUB_WORKSPACE/mo-tester
          ./run.sh -n -g -p $GITHUB_WORKSPACE/test/distributed/cases 2>&1

      - name: export log
        if: ${{ always() }}
        run: |
          mkdir ${{ github.workspace }}/docker-compose-log
          docker compose -f etc/launch-tae-compose/compose.yaml --profile launch-tae-multi-CN-tae-DN logs cn-0 > docker-compose-log/cn-0.log
          docker compose -f etc/launch-tae-compose/compose.yaml --profile launch-tae-multi-CN-tae-DN logs cn-1 > docker-compose-log/cn-1.log
          docker compose -f etc/launch-tae-compose/compose.yaml --profile launch-tae-multi-CN-tae-DN logs dn > docker-compose-log/dn.log
          docker compose -f etc/launch-tae-compose/compose.yaml --profile launch-tae-multi-CN-tae-DN logs logService > docker-compose-log/logService.log

      - name: shutdown containers
        if: ${{ always() }}
        run: |
          docker compose -f etc/launch-tae-compose/compose.yaml --profile launch-tae-multi-CN-tae-DN down --remove-orphans
          docker volume rm launch-tae-compose_minio_storage

      - uses: actions/upload-artifact@v2
        if: ${{ failure() || cancelled()}}
        continue-on-error: true
        with:
          name: multi-cn-e2e_docker-compose
          path: |
            docker-compose-log
          retention-days: 7
