name:  Build and Push Images

on:
  schedule:
    - cron: '0 22 * * *'
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: matrixorigin/CI/.github/workflows/image-build.yaml@main
    with:
      repo: "matrixone"
      region: "us-east-1"
      alias: "p4n7f8j9"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_TOKEN: ${{ secrets.ACR_TOKEN }}
      AWS_ROLE: ${{ secrets.AWS_ROLE }}
