name:  Build My Image

on:
  workflow_dispatch:

jobs:
  docker_image_build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: BUILD MY MO DOCKER IMAGE

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Prepare
        id: prep
        run: |
          LAST_COMMIT_ID=$(git rev-parse --short HEAD)
          DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/matrixone
          VERSION=commit-$LAST_COMMIT_ID

          TAGS="${DOCKER_IMAGE}:${VERSION}"

          # Set output parameters.
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "docker_image=${DOCKER_IMAGE}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          
      - name: Build && Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./optools/images//Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}
                
  
