name:  Build My Image

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Prepare
        id: prep
        run: |
          pwd
          ls -al
          echo ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_IMAGE='nnsmgsone/matrixone'
          VERSION=nightly-${GITHUB_SHA::8}
          
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          
          # Set output parameters.
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "docker_image=${DOCKER_IMAGE}" >> $GITHUB_OUTPUT

      - name: Get image info
        run: |
          echo image-tags: ${{ steps.prep.outputs.tags }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./optools/images/Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}
